#!/usr/bin/env node
//
// Writes builder.html — the page builder, creator 3 (roadmap §4.12). Generated
// and committed like kitchen-sink.html and portal.html, for the same reason:
// everything on it derives from files on disk, and a hand-maintained copy
// would drift. `npm run builder`; regenerated by `npm run verify`.
//
// WHAT THE PAGE IS. A template picker, four answers (theme, prefix, name,
// title) plus the page file name, and a live
// preview of the page those choices produce — in an iframe, because the
// composed page has its own header and rendering it inline here would show
// two shells, which is exactly what roadmap §4.12's "no frames" line forbids.
// A block picker and its text fields came next, because a builder that cannot
// reproduce an unedited template byte for byte has no business editing one and
// that round trip is proved first. Then the catalogue and the arrangement: a
// slot, every marked block to add to it, and move and remove on the selected
// one, with the page model in builder/page.mjs. Then undo, redo and a draft
// that survives a reload, so nothing after this stage grows what can be
// edited without a way back. Then export (held byte for byte to the scaffold
// script by check-parity until both retired on 2026-09-12; the builder is the
// one page-writer now). Then content that reads as content: every field named
// by what it IS, grouped, with its original beside it and a link target where
// the markup has one. Then the two things about a block that are a CHOICE
// rather than content: how big its buttons are and how tight its table rows,
// as class swaps whose spellings Carbon and this repository already attest.
// Then the GUIDED MODE (stage 12): the same controls, grouped into five
// sections — Purpose, Sections and content, Add sections, Review, Take it
// away — shown one at a time behind a vertical progress indicator, or all at
// once in the free mode. ONE SET OF DOM NODES, TWO WAYS OF SHOWING THEM: the
// modes share every control, the draft, the model and the history, and a
// mode is where the reader is standing, never a change.
//
// EVERYTHING A MODE HIDES IS WRAPPED IN A PLAIN <div>. `.rux--progress` and
// `.rux--form-item` are display:flex, and .bld-row is too, so `hidden` on any
// of them would lose to the author rule on origin — the exact defect fixed for
// `.rux--btn[hidden]` on 2026-09-02. A classless <div> takes the attribute
// and the browser's own [hidden] rule holds. A <section> DOES NOT: Carbon's
// reset sets display:block on the HTML5 sectioning elements, which beats
// [hidden] the same way, and the first browser run showed every step at once
// with the attributes correctly set. So the five steps carry .bld-step and
// the inline style below writes .bld-step[hidden] { display: none } — the
// override's own pattern, at the builder's own class.
//
// THE STEPPER'S GLYPHS ARE SWAPPED AT RUNTIME, and the third one is asserted
// by name. Carbon draws the vertical indicator's svg at display:inline-block
// on the button, which beats [hidden], so builder.js changes the <use> rather
// than toggling three svgs. The file ships step 1 current and four not
// started, so #i-checkmark--outline never appears in the markup; RUNTIME_GLYPHS
// below names it, and the assertion at the foot reads that list beside the
// markup. A glyph builder.js writes and nothing asserts would paint nothing,
// silently, which is the failure that assertion exists to stop.
//
// TWO CONTROLS PER STATE where the guided one has to say more: the template
// select (free) beside a radio group labelled by the map's purpose line
// (guided), and the block select (free) beside a contained list of the page's
// units (guided). Both write the same state through the same handler in
// builder.js. The purpose lines are read from builder/guide.json HERE, at
// build time, so the radios are static markup check-classes can read; an
// unreviewed line keeps its "(not reviewed)" suffix exactly as the page's
// runtime suggestion list spells it.
//
// TWO NOTICE TEMPLATES, BOTH FULLY WRITTEN HERE. The draft notice and the
// save-failure alert are the same attested composition in two variants, and
// each is spelled out rather than built by swapping a modifier at runtime,
// because the icon differs — the assertion at the foot reads the glyphs in
// THIS file and cannot see builder.js, so a `<use>` only JavaScript names
// would go unchecked. Both are sink/notification.html's ACTIONABLE specimen,
// which is where an action button beside a close button is attested.
//
// AND THEY ARE <template>s, NOT `hidden` MARKUP. `.rux--actionable-notification`
// is display:flex, which beats the browser's `[hidden]` on origin — the exact
// defect fixed for `.rux--btn[hidden]` on 2026-09-02 (css/rux-overrides.css).
// Cloning also keeps check-runtime-classes honest: DOMParser does not descend
// into template content, so these classes are invisible to both its sides
// until one is cloned, when they read as ADDED, the harmless direction.
//
// NO SPRITE MARKERS. tools/lib/sources.mjs spritePages() hands any root page
// carrying SPRITE:BEGIN to `npm run icons` as a writer; this file is already
// that page's writer, and two writers on one region is the drift the markers
// exist to stop. assets/icons.svg is inlined here directly, and every glyph
// the page uses is asserted against it — the build-portal-icons pattern —
// because a <use> at a missing symbol paints nothing, silently.
//
// THE CHROME IS bld-. Layout the builder itself needs — the preview box, the
// width row — is an inline <style> on --rux-* tokens with bld- classes, which
// check-classes ignores exactly as it ignores the sink's ks-, and which
// check-tokens reads because this is a root page. The component markup is
// the sink's own (select, radio group, text input, buttons) and the shell is
// portal.html's, header-only.
//
// THE PREVIEW IS OUTSIDE EVERY GATE. check-a11y and the rest query the top
// document and do not descend into an iframe; sweeping this page measures the
// builder's chrome, not the page inside it. The page says so.
import { readFileSync, writeFileSync } from 'node:fs';
import { shell, shellHead, shellScripts } from './lib/shell.mjs';

const sprite = readFileSync('assets/icons.svg', 'utf8').trim();
const symbols = new Set([...sprite.matchAll(/<symbol\s+id="([^"]+)"/g)].map(m => m[1]));

const guide = JSON.parse(readFileSync('builder/guide.json', 'utf8'));
// A glyph the page shows only after builder.js writes it. See the header.
const RUNTIME_GLYPHS = ['i-checkmark--outline'];

const THEMES = [['white', 'White'], ['g10', 'Gray 10'], ['g90', 'Gray 90'], ['g100', 'Gray 100'], ['geist', 'Geist'], ['linear', 'Linear'], ['ant-dark', 'Ant Dark'], ['spotify', 'Spotify']];
const GRIDS = [['capped', 'Capped at 99rem'], ['full', 'Full width']];
const STEPS = [['Purpose', 'What the page is for'], ['Sections and content', 'Each part, its words and its size'], ['Add sections', 'What else the page could carry'], ['Review', 'How it looks and whether it holds together'], ['Take it away', 'The file, or the command that makes a project']];
const esc = t => String(t).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
// The purpose radios: sink/radio.html's group, vertical, one per template in
// the map's order, labelled name first (the identity) and purpose after.
const PURPOSES = Object.entries(guide.templates).map(([name, t]) => `                  <div class="rux--radio-button-wrapper">
                    <input id="bld-purpose-${name}" class="rux--radio-button" type="radio" name="bld-purpose" value="${name}"${name === 'app-shell' ? ' checked' : ''}>
                    <label for="bld-purpose-${name}" class="rux--radio-button__label">
                      <span class="rux--radio-button__appearance"></span>
                      <span class="rux--radio-button__label-text">${name} — ${esc(t.purpose)}${t.reviewed ? '' : ' (not reviewed)'}</span>
                    </label>
                  </div>`).join('\n');
// The stepper, sink/progress-indicator.html's vertical specimen with every
// step CLICKABLE — no --unclickable — so the reader can go back and forth.
const STEPPER = STEPS.map(([label], i) => `                  <li class="rux--progress-step rux--progress-step--${i === 0 ? 'current' : 'incomplete'}">
                    <button type="button" class="rux--progress-step-button" data-step="${i + 1}">
                      <svg width="16" height="16" viewBox="0 0 32 32" aria-hidden="true"><use href="#${i === 0 ? 'i-incomplete' : 'i-circle-dash'}"/></svg>
                      <div class="rux--progress-text"><span class="rux--progress-label">${label}</span></div>
                      <span class="rux--assistive-text">${i === 0 ? 'Current' : 'Not started'}</span>
                      <span class="rux--progress-line"></span>
                    </button>
                  </li>`).join('\n');
const WIDTHS = [['375', '375'], ['672', '672'], ['1056', '1056'], ['1280', '1280'], ['1440', '1440'], ['fit', 'Fit']];

const textInput = (id, label, placeholder, helper) => `
          <div class="rux--form-item rux--text-input-wrapper">
            <div class="rux--text-input__label-wrapper">
              <label class="rux--label" for="${id}">${label}</label>
            </div>
            <div class="rux--text-input__field-outer-wrapper">
              <div class="rux--text-input__field-wrapper">
                <input id="${id}" class="rux--text-input" type="text" placeholder="${placeholder}">
              </div>
            </div>
            <div class="rux--form__helper-text">${helper}</div>
          </div>`;

const page = `<!doctype html>
<html lang="en" data-theme="white">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>rux-ds — builder</title>
<link rel="icon" href="brand/favicon.svg" type="image/svg+xml">
<link rel="preload" as="font" type="font/woff2" crossorigin href="assets/fonts/IBMPlexSans-Regular-Latin1.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin href="assets/fonts/IBMPlexSans-SemiBold-Latin1.woff2">
<link rel="preload" as="font" type="font/woff2" crossorigin href="assets/fonts/IBMPlexMono-Regular-Latin1.woff2">
<link rel="stylesheet" href="assets/fonts/plex.css">
<link rel="stylesheet" href="css/rux.css">
<link rel="stylesheet" href="css/rux-theme.css">
<link rel="stylesheet" href="css/rux-overrides.css">
${shellHead()}
<style>
/* The builder's own layout, bld- so check-classes ignores it the way it
   ignores the sink's ks-. Tokens only; no colour or size is invented. */
.bld-preview { background: var(--rux-layer-01); border: 1px solid var(--rux-border-subtle-01); padding: var(--rux-spacing-05); overflow: auto; }
.bld-frame-wrap { transform-origin: top left; }
.bld-frame { display: block; inline-size: 100%; block-size: 48rem; border: 0; background: var(--rux-background); }
.bld-widths, .bld-row { display: flex; flex-wrap: wrap; gap: var(--rux-spacing-03); }
.bld-status { color: var(--rux-text-secondary); }
/* A warning about the page being composed, not about the builder. Tokens only:
   --rux-support-error is the theme's own, so it follows a theme change like
   everything else on the page. */
.bld-warn { color: var(--rux-support-error); }
.bld-suggest { border-inline-start: 2px solid var(--rux-border-subtle-01); padding-inline-start: var(--rux-spacing-04); }
.bld-suggest p { margin: 0 0 var(--rux-spacing-02); }
/* A step shown one at a time. Carbon's reset gives <section> display:block,
   which beats the browser's [hidden] on origin, so the attribute is honoured
   here — the same shape as .rux--btn[hidden] in css/rux-overrides.css. */
.bld-step { min-inline-size: 0; }
.bld-step[hidden] { display: none; }
</style>
</head>
<body>
<!-- GENERATED by tools/build-builder.mjs — do not edit. Edit the generator. -->
<!-- PROVENANCE: rendered-dom · the shell is portal.html's, header-only, from
     components-ui-shell-header--header-w-navigation-actions-and-side-nav
     captured 2026-08-31; the controls are sink/select.html, sink/radio.html,
     sink/text-input.html and sink/buttons.html markup, verbatim -->
<!-- BEHAVIOUR: derived · builder/builder.js is rux's own, not Carbon's: it
     composes a template from builder/blocks.json and previews it. What the
     gates measure on this page is its chrome. NOT COVERED, by construction:
     anything inside the preview iframe — check-a11y, check-spacing and
     check-runtime-classes read the top document only. The exported page is
     the thing to sweep, and nothing here will do that once it leaves. -->

${sprite}

${shell('builder')}

<main id="main-content" class="rux--content">
  <div class="rux--css-grid">
    <div class="rux--css-grid-column rux--col-span-100">
      <div class="rux--stack-vertical rux--stack-scale-7">
        <div class="rux--stack-vertical rux--stack-scale-5">
          <h1>Page builder</h1>
          <p>Start from a template and see the page it makes. The preview is the real page in a frame of its own; what it cannot promise is the composition — every part is attested, the arrangement is yours, and <code>docs/composing-pages.md</code> §3.10 says what that means.</p>
        </div>
        <div id="bld-notice"></div>
        <div class="rux--subgrid rux--subgrid--wide rux--subgrid--with-row-gap">

          <div class="rux--css-grid-column rux--sm:col-span-4 rux--md:col-span-8 rux--lg:col-span-5">
            <div class="rux--stack-vertical rux--stack-scale-7">
              <div class="bld-row" role="group" aria-label="History">
                <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-undo" disabled>Undo</button>
                <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-redo" disabled>Redo</button>
                <button type="button" class="rux--btn rux--btn--danger--ghost rux--btn--sm rux--layout--size-sm" id="bld-start-over">Start over</button>
              </div>
              <div class="bld-row" role="group" aria-label="Mode">
                <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" data-mode="guided" aria-pressed="true">Guided</button>
                <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" data-mode="free" aria-pressed="false">Free</button>
              </div>
              <div id="bld-stepper">
                <ul class="rux--progress rux--progress--vertical" aria-label="Steps">
${STEPPER}
                </ul>
              </div>

              <section class="bld-step" data-step="1" aria-labelledby="bld-h-1">
                <div class="rux--stack-vertical rux--stack-scale-7">
                  <h2 id="bld-h-1" tabindex="-1">Purpose</h2>
                  <div id="bld-purpose">
                    <div class="rux--form-item">
                      <fieldset class="rux--radio-button-group rux--radio-button-group--label-right rux--radio-button-group--vertical">
                        <legend class="rux--label">What is this page for?</legend>
${PURPOSES}
                      </fieldset>
                      <div class="rux--form__helper-text">The ten shapes in <code>templates/</code>, each a complete page. Pick the nearest job; every part can be changed after.</div>
                    </div>
                  </div>
                  <div id="bld-template-free">
                    <div class="rux--form-item">
                      <div class="rux--select">
                        <label class="rux--label" for="bld-template">Template</label>
                        <div class="rux--select-input__wrapper">
                          <select id="bld-template" class="rux--select-input"></select>
                          <svg class="rux--select__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--down"/></svg>
                        </div>
                        <div class="rux--form__helper-text">One of the ten in <code>templates/</code>.</div>
                      </div>
                    </div>
                  </div>
                  <div class="rux--form-item">
                    <fieldset class="rux--radio-button-group rux--radio-button-group--label-right rux--radio-button-group--vertical" id="bld-theme">
                      <legend class="rux--label">Default theme</legend>
${THEMES.map(([v, l]) => `                      <div class="rux--radio-button-wrapper">
                        <input id="bld-theme-${v}" class="rux--radio-button" type="radio" name="bld-theme" value="${v}"${v === 'white' ? ' checked' : ''}>
                        <label for="bld-theme-${v}" class="rux--radio-button__label">
                          <span class="rux--radio-button__appearance"></span>
                          <span class="rux--radio-button__label-text">${l}</span>
                        </label>
                      </div>`).join('\n')}
                    </fieldset>
                    <div class="rux--form__helper-text">The page's default. A visitor's own choice, saved in the account panel, wins on the real page; the preview shows the default.</div>
                  </div>
                  <div class="rux--form-item">
                    <fieldset class="rux--radio-button-group rux--radio-button-group--label-right rux--radio-button-group--vertical" id="bld-grid">
                      <legend class="rux--label">Grid width</legend>
${GRIDS.map(([v, l]) => `                      <div class="rux--radio-button-wrapper">
                        <input id="bld-grid-${v}" class="rux--radio-button" type="radio" name="bld-grid" value="${v}"${v === 'capped' ? ' checked' : ''}>
                        <label for="bld-grid-${v}" class="rux--radio-button__label">
                          <span class="rux--radio-button__appearance"></span>
                          <span class="rux--radio-button__label-text">${l}</span>
                        </label>
                      </div>`).join('\n')}
                    </fieldset>
                    <div class="rux--form__helper-text">Capped is Carbon's reading width, centred, and right for prose and forms. Full width is Carbon's own modifier for a page that is scanned rather than read &mdash; a board, a wide table &mdash; and only shows above 99rem.</div>
                  </div>${textInput('bld-prefix', 'Product prefix', 'Rux', 'The lighter-weight half of the header name.')}${textInput('bld-name', 'Product name', 'DS', 'The header name and its aria-label.')}${textInput('bld-title', 'Browser tab title', 'Prefix and name', 'Defaults to the prefix and the name, as the script does.')}
                </div>
              </section>

              <section class="bld-step" data-step="2" aria-labelledby="bld-h-2">
                <div class="rux--stack-vertical rux--stack-scale-7">
                  <h2 id="bld-h-2" tabindex="-1">Sections and content</h2>
                  <div id="bld-outline">
                    <div class="rux--contained-list rux--layout--size-lg rux--contained-list--on-page">
                      <div class="rux--contained-list__header"><h3 class="rux--contained-list__label">On the page</h3></div>
                      <ul role="list" id="bld-outline-list"></ul>
                    </div>
                    <div class="rux--form__helper-text">Every section in order, top to bottom. Choose one to edit it below; a part that moves with another is named on its row.</div>
                  </div>
                  <div id="bld-picker-free">
                    <div class="rux--form-item">
                      <div class="rux--select">
                        <label class="rux--label" for="bld-block">Block on the page</label>
                        <div class="rux--select-input__wrapper">
                          <select id="bld-block" class="rux--select-input"></select>
                          <svg class="rux--select__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--down"/></svg>
                        </div>
                        <div class="rux--form__helper-text">Every block on the page, in order; a second copy is numbered.</div>
                      </div>
                    </div>
                  </div>
                  <div class="bld-row" role="group" aria-label="Arrange the selected block">
                    <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-up">Move up</button>
                    <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-down">Move down</button>
                    <button type="button" class="rux--btn rux--btn--danger--ghost rux--btn--sm rux--layout--size-sm" id="bld-remove">Remove</button>
                  </div>
                  <p class="bld-status" id="bld-keep-line">Keeping it. Next moves on; Remove takes it off the page, and Undo brings it back.</p>
                  <div class="rux--stack-vertical rux--stack-scale-5" id="bld-fields"></div>
                  <div id="bld-keep-wrap">
                    <div class="bld-row" role="group" aria-label="Settings for this section">
                      <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-keep" disabled>Keep attested settings</button>
                    </div>
                    <div class="rux--form__helper-text" id="bld-keep-note"></div>
                  </div>
                  <div>
                    <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-reset" disabled>Reset content</button>
                  </div>
                  <ul class="rux--accordion rux--accordion--end rux--layout--size-md">
                    <li class="rux--accordion__item">
                      <button type="button" class="rux--accordion__heading" aria-expanded="false">
                        <svg class="rux--accordion__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--right"/></svg>
                        <div class="rux--accordion__title">Details</div>
                      </button>
                      <div class="rux--accordion__wrapper">
                        <div class="rux--accordion__content">
                          <p class="bld-status" id="bld-block-note"></p>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </section>

              <section class="bld-step" data-step="3" aria-labelledby="bld-h-3">
                <div class="rux--stack-vertical rux--stack-scale-7">
                  <h2 id="bld-h-3" tabindex="-1">Add sections</h2>
                  <div id="bld-suggestions" hidden></div>
                  <h3 class="rux--type-heading-compact-01">Inspect the catalogue</h3>
                  <div class="rux--form-item">
                    <div class="rux--select">
                      <label class="rux--label" for="bld-slot">Slot</label>
                      <div class="rux--select-input__wrapper">
                        <select id="bld-slot" class="rux--select-input"></select>
                        <svg class="rux--select__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--down"/></svg>
                      </div>
                      <div class="rux--form__helper-text" id="bld-slot-note">A container the template already has.</div>
                    </div>
                  </div>
                  <div class="rux--form-item">
                    <div class="rux--select">
                      <label class="rux--label" for="bld-catalogue">Seen in the same recorded layout</label>
                      <div class="rux--select-input__wrapper">
                        <select id="bld-catalogue" class="rux--select-input"></select>
                        <svg class="rux--select__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--down"/></svg>
                      </div>
                      <div class="rux--form__helper-text" id="bld-catalogue-note">Blocks recorded in a container with the same grid, column and stack classes as this slot. That is evidence, not a verdict: only a block in its own slot is an attested placement. Added to the end of the slot.</div>
                    </div>
                  </div>
                  <div>
                    <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-add">Add to slot</button>
                  </div>
                  <p class="bld-warn" id="bld-frame-note" hidden></p>
                  <ul class="rux--accordion rux--accordion--end rux--layout--size-md">
                    <li class="rux--accordion__item">
                      <button type="button" class="rux--accordion__heading" aria-expanded="false" id="bld-rest-toggle">
                        <svg class="rux--accordion__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--right"/></svg>
                        <div class="rux--accordion__title" id="bld-rest-title">No matching recorded layout</div>
                      </button>
                      <div class="rux--accordion__wrapper">
                        <div class="rux--accordion__content">
                          <div class="rux--form-item">
                            <div class="rux--select">
                              <label class="rux--label" for="bld-rest">Add anyway</label>
                              <div class="rux--select-input__wrapper">
                                <select id="bld-rest" class="rux--select-input"></select>
                                <svg class="rux--select__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--down"/></svg>
                              </div>
                              <div class="rux--form__helper-text">No capture places these here. Every part is still attested on its own; what is unverified is the arrangement, and there may be no fix — <code>docs/composing-pages.md</code> §3.10.</div>
                            </div>
                          </div>
                          <p class="bld-warn" id="bld-rest-frame-note" hidden></p>
                          <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-add-rest">Add to slot</button>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </section>

              <section class="bld-step" data-step="4" aria-labelledby="bld-h-4">
                <div class="rux--stack-vertical rux--stack-scale-7">
                  <h2 id="bld-h-4" tabindex="-1">Review</h2>
                  <div class="rux--stack-vertical rux--stack-scale-3">
                    <h3 class="rux--type-heading-compact-01">Preview width</h3>
                    <div class="bld-widths" role="group" aria-label="Preview width">
${WIDTHS.map(([v, l]) => `                      <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" data-width="${v}" aria-pressed="${v === 'fit'}">${l}</button>`).join('\n')}
                    </div>
                    <div class="rux--form__helper-text">The preview is the real page in a frame of its own. Try the four widths the grid breaks at, and Fit for the pane.</div>
                  </div>
                  <p class="bld-status" id="bld-review"></p>
                  <div>
                    <a class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-open" href="#" target="_blank" rel="noopener">Open in a new tab</a>
                  </div>
                  <div class="rux--form__helper-text">The same page the frame shows, on its own, so its header and account panel can be tried at full size.</div>
                </div>
              </section>

              <section class="bld-step" data-step="5" aria-labelledby="bld-h-5">
                <div class="rux--stack-vertical rux--stack-scale-7">
                  <h2 id="bld-h-5" tabindex="-1">Take it away</h2>${textInput('bld-page', 'File name', 'index', 'Without .html — what the export downloads as.')}
                  <div id="bld-export-notice"></div>
                  <p class="bld-status" id="bld-export-warn" hidden></p>
                  <div class="rux--stack-vertical rux--stack-scale-5">
                    <div class="rux--stack-vertical rux--stack-scale-3">
                      <h3 class="rux--type-heading-compact-01">A page for an existing project</h3>
                      <div class="bld-row" role="group" aria-label="Take the page away">
                        <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-download">Download the page</button>
                        <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-copy">Copy the main region</button>
                      </div>
                      <div class="rux--form__helper-text">The download goes beside the project's <code>index.html</code>, and its paths already point at <code>/rux-ds/</code>. The copy is the whole <code>&lt;main&gt;</code> element, so it REPLACES a page's main region rather than filling it.</div>
                    </div>
                    <div class="rux--stack-vertical rux--stack-scale-3">
                      <h3 class="rux--type-heading-compact-01">A new app</h3>
                      <div class="rux--form__helper-text">Make a folder named for its URL beside <code>rux-ds/</code> in the site repository, save the download there as <code>index.html</code>, and add one entry to <code>switcher.json</code>. The next push publishes it. Nothing else to run: the scaffold script that used to do this left on 2026-09-12.</div>
                    </div>
                  </div>
                </div>
              </section>

              <div id="bld-nav">
                <div class="bld-row" role="group" aria-label="Move between steps">
                  <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-back" disabled>Back</button>
                  <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" id="bld-next">Next</button>
                </div>
              </div>
            </div>
          </div>

          <div class="rux--css-grid-column rux--sm:col-span-4 rux--md:col-span-8 rux--lg:col-span-11">
            <div class="rux--stack-vertical rux--stack-scale-5">
              <h2>Preview</h2>
              <p class="bld-status" id="bld-status">Loading the catalogue…</p>
              <p class="bld-status" id="bld-integrity" hidden></p>
              <div class="bld-preview">
                <div class="bld-frame-wrap" id="bld-frame-wrap">
                  <iframe class="bld-frame" id="bld-frame" title="Preview of the composed page"></iframe>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</main>

<!-- CLONED, NEVER CONSTRUCTED. builder/builder.js says it invents no rux--
     markup; a field row is real component markup, so it ships here where
     check-classes reads it and is only cloned at runtime. The field row is
     templates/form-page.html's own text-area composition minus maxlength,
     placeholder and the counter-alert span — nothing here counts characters,
     and an empty role="alert" region would ship for no reason. cols goes too,
     and that one was measured rather than reasoned: cols is a flex item's
     min-content floor, so the source's cols="50" rendered 403px wide inside
     this 388px column and overflowed it. The wrapper is already inline-size
     100%. id and for are set per clone.
     THE HELPER LINE NOW CARRIES THE ORIGINAL, and ships hidden because a
     row with no edit and a named role has nothing to say there; the reset
     button ships hidden for the same reason and is revealed only while that
     one field differs from its source. Both are real markup here rather than
     constructed in builder.js, the rule this file's header states.
     (No backticks in this comment: it lives inside a template literal, and
     one closed the string.) -->
<template id="bld-field-template">
  <div class="rux--form-item">
    <div class="rux--text-area__label-wrapper">
      <label class="rux--label"></label>
    </div>
    <div class="rux--text-area__wrapper">
      <textarea class="rux--text-area" rows="2"></textarea>
    </div>
    <div class="rux--form__helper-text" hidden></div>
    <div>
      <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" hidden>Reset this field</button>
    </div>
  </div>
</template>
<!-- The heading over a group of fields, and the group itself. Both are cloned
     per group; the h3 is the same rux--type-heading-compact-01 the Export
     section uses, and the role="group" is the pattern .bld-row already
     carries. The aria-label is written per clone and is never empty: a
     cleared label falls back to the structural name. -->
<!-- A VARIANT ROW: the select, the "as attested" note and the reset, cloned
     per group. It is sink/select.html's own composition, the same one the
     Choices column uses, because the values are a short closed list rather
     than free text. The helper line and the reset ship hidden for the reason
     the field row's do: a group nobody has changed has nothing to say. -->
<template id="bld-variant-template">
  <div class="rux--form-item">
    <div class="rux--select">
      <label class="rux--label"></label>
      <div class="rux--select-input__wrapper">
        <select class="rux--select-input"></select>
        <svg class="rux--select__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--down"/></svg>
      </div>
      <div class="rux--form__helper-text" hidden></div>
    </div>
    <div>
      <button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" hidden>Reset this group</button>
    </div>
  </div>
</template>
<template id="bld-group-template">
  <div role="group" aria-label="">
    <h3 class="rux--type-heading-compact-01"></h3>
  </div>
</template>
<template id="bld-suggest-group-template">
  <ul class="rux--accordion rux--accordion--end rux--layout--size-md">
    <li class="rux--accordion__item">
      <button type="button" class="rux--accordion__heading" aria-expanded="false">
        <svg class="rux--accordion__arrow" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-chevron--right"/></svg>
        <div class="rux--accordion__title"></div>
      </button>
      <div class="rux--accordion__wrapper">
        <div class="rux--accordion__content"></div>
      </div>
    </li>
  </ul>
</template>
<template id="bld-suggest-template">
  <div class="bld-suggest">
    <p data-role="reason"></p>
    <p class="bld-status" data-role="unless" hidden></p>
    <p class="bld-warn" data-role="evidence" hidden></p>
    <p><button type="button" class="rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm" data-act="add">Add</button></p>
  </div>
</template>
<!-- One row of the outline: sink/contained-list.html's clickable item. The
     text is written per clone; aria-current marks the unit the panel below
     is editing. -->
<template id="bld-outline-item-template">
  <li class="rux--contained-list-item rux--contained-list-item--clickable">
    <button type="button" class="rux--contained-list-item__content"></button>
  </li>
</template>
<template id="bld-no-fields-template">
  <p class="rux--form__helper-text">This block has no text to edit.</p>
</template>
<template id="bld-notice-template">
  <div class="rux--actionable-notification rux--actionable-notification--info" role="alertdialog">
    <span class="rux--visually-hidden" role="link">Beginning of notification</span>
    <div class="rux--actionable-notification__focus-wrapper">
      <div class="rux--actionable-notification__details">
        <svg class="rux--inline-notification__icon" width="20" height="20" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-information--filled"/></svg>
        <div class="rux--actionable-notification__text-wrapper">
          <div class="rux--actionable-notification__content">
            <div class="rux--actionable-notification__title"></div>
            <div class="rux--actionable-notification__subtitle"></div>
          </div>
        </div>
      </div>
      <div class="rux--actionable-notification__button-wrapper">
        <button type="button" class="rux--actionable-notification__action-button rux--btn rux--btn--ghost rux--btn--sm rux--layout--size-sm"></button>
        <button type="button" class="rux--actionable-notification__close-button" aria-label="Close">
          <svg class="rux--actionable-notification__close-icon" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-close"/></svg>
        </button>
      </div>
    </div>
    <span class="rux--visually-hidden" role="link">End of notification</span>
  </div>
</template>
<template id="bld-alert-template">
  <div class="rux--actionable-notification rux--actionable-notification--error" role="alertdialog">
    <span class="rux--visually-hidden" role="link">Beginning of notification</span>
    <div class="rux--actionable-notification__focus-wrapper">
      <div class="rux--actionable-notification__details">
        <svg class="rux--inline-notification__icon" width="20" height="20" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-error--filled"/></svg>
        <div class="rux--actionable-notification__text-wrapper">
          <div class="rux--actionable-notification__content">
            <div class="rux--actionable-notification__title"></div>
            <div class="rux--actionable-notification__subtitle"></div>
          </div>
        </div>
      </div>
      <div class="rux--actionable-notification__button-wrapper">
        <button type="button" class="rux--actionable-notification__close-button" aria-label="Close">
          <svg class="rux--actionable-notification__close-icon" width="16" height="16" viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><use href="#i-close"/></svg>
        </button>
      </div>
    </div>
    <span class="rux--visually-hidden" role="link">End of notification</span>
  </div>
</template>

<script src="js/overlay.js"></script>
<script src="js/popover.js"></script>
<script src="js/menu.js"></script>
<script src="js/list-box.js"></script>
<script src="js/tabs.js"></script>
<script src="js/accordion.js"></script>
<script src="js/data-table.js"></script>
<script src="js/form-controls.js"></script>
<script src="js/ui-shell.js"></script>
<script src="js/dismiss.js"></script>
<script src="js/tile.js"></script>
<script src="js/modal.js"></script>
${shellScripts()}
<script type="module" src="builder/builder.js"></script>
</body>
</html>
`;

// Every glyph this page references must exist in the sprite it inlines.
const body = page.slice(page.indexOf('</svg>') + 6);
const missing = [...new Set([...[...body.matchAll(/<use\s+href="#(i-[^"]+)"/g)].map(m => m[1]), ...RUNTIME_GLYPHS])].filter(id => !symbols.has(id));
if (missing.length) {
  for (const id of missing) console.log(`  build-builder: no <symbol id="${id}"> in assets/icons.svg`);
  process.exit(1);
}
writeFileSync('builder.html', page);
console.log(`  builder.html — ${(page.length / 1024).toFixed(0)} KB · ${symbols.size} symbols inlined`);
