#!/usr/bin/env node
//
// Writes builder/blocks.json — the page builder's catalogue — from the BLOCK
// and SLOT markers in sink/*.html and templates/*.html. Roadmap §4.12, creator 3.
//   node tools/build-blocks.mjs        (npm run blocks)
//
// WHY A MANIFEST AND NOT THE FRAGMENTS. A sink fragment is a demo catalogue —
// the section, its heading, several specimens under ks-label headings with
// inline demo styles — and ks-* is defined only in sink/harness.css, never in
// css/rux.css. A fragment dropped into a real page carries wrappers that style
// nothing. The markers say which region IS the block; this file copies exactly
// that region, byte for byte, and tools/check-blocks.mjs fails if a copy has
// drifted from its source. The sink stays the single place the markup lives.
//
// TWO PROVENANCES BY DESIGN. sink/* gives components; templates/* gives
// compositions — a dashboard's four-across metric row is a template block, not
// four sink tiles, because the subgrid with its per-breakpoint spans is what
// was attested. A template's blocks come with their slots: the containers
// they were measured in, whose classes are recorded so the builder can say
// where else the same block may honestly go.
//
// WHY GENERATED AND COMMITTED. builder.html fetches this at runtime, and a
// catalogue typed by hand would drift the first time a fragment is renamed —
// the same reason kitchen-sink.html derives its nav and portal.html derives
// its every figure. builder/ is read by no gate: pageFiles() lists the root
// non-recursively and markupFiles() reads sink and templates, so nothing here
// is accidentally claimed as covered. check-blocks is what covers it.
//
// DETERMINISTIC. No timestamp, sorted by source then position, so `npm run
// verify` leaves a clean tree when nothing changed and CI can diff the file.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { markupFiles } from './lib/sources.mjs';
import { scan, manifestOf } from './lib/blocks.mjs';
import { COVERAGE, BEGIN, END, coverageTable, coverageRows } from './lib/coverage.mjs';

const OUT = 'builder/blocks.json';
const faults = [];

const entries = [];
for (const f of markupFiles(['sink', 'templates'])) {
  const html = readFileSync(f.path, 'utf8');
  const r = scan(html, f.path);
  faults.push(...r.faults);
  entries.push({ path: f.path, root: f.root, html, scan: r });
}

// WHAT A RECORD IS lives in lib/blocks.mjs, so check-blocks re-derives it with
// this same code and compares. Nothing about the catalogue is decided here.
const { blocks, templates } = manifestOf(entries);

// The table is derived in lib/coverage.mjs so check-blocks re-derives it with
// the same code. Only the region between the markers is ours; everything else
// on that page is hand-written, the arrangement build-readme.mjs uses on README.
function writeCoverage() {
  const body = readFileSync(COVERAGE, 'utf8');
  const a = body.indexOf(BEGIN), b = body.indexOf(END);
  if (a === -1 || b === -1) {
    faults.push(['NO MARKERS', COVERAGE, `needs ${BEGIN} and ${END} — the generated table goes between them and nothing else is touched`]);
    return;
  }
  writeFileSync(COVERAGE, body.slice(0, a + BEGIN.length) + '\n' + coverageTable(blocks) + '\n' + body.slice(b));
  const rows = coverageRows(blocks);
  console.log(`  ${COVERAGE} — ${rows.length} fragments · ${rows.filter(r => r.blocks).length} marked`);
}

if (faults.length) {
  console.log(`\n  build-blocks: ${faults.length} marker fault${faults.length === 1 ? '' : 's'} — nothing written`);
  process.exit(1);
}

const manifest = {
  _: 'GENERATED by tools/build-blocks.mjs — do not edit. Every block `html` is a verbatim copy of a BLOCK region in sink/ or templates/, and every slot record reassembles to its file byte for byte; tools/check-blocks.mjs fails if either drifts. Edit the marked source and run `npm run blocks`.',
  blocks, templates,
};
mkdirSync('builder', { recursive: true });
writeFileSync(OUT, JSON.stringify(manifest, null, 2) + '\n');
const files = new Set(blocks.map(b => b.source)).size;
const slots = templates.reduce((n, t) => n + t.slots.length, 0);
console.log(`  ${OUT} — ${blocks.length} blocks in ${files} files · ${templates.length} templates · ${slots} slots`);
if (existsSync(COVERAGE)) writeCoverage();
