#!/usr/bin/env node
//
// Snapshot the GEOMETRY of every glyph our sprite claims, from @carbon/icons.
//
// WHY A SNAPSHOT AND NOT A DIRECT READ. check-glyphs could open
// node_modules/@carbon/icons on every run, and for as long as the package is
// vendored that would be simpler. Phase 4 removes it — roadmap's one-way door —
// and a gate that dies at devendor is a gate that gets deleted at devendor. The
// captures in docs/ exist for exactly this reason; this file joins them.
//
// WHAT IS RECORDED, and it is deliberately narrow: only the names our sprite
// already carries. @carbon/icons ships thousands, and a snapshot of all of them
// would be a vendored copy of the package wearing a different hat. This records
// the reference for what we actually claim, which is the only thing a gate can
// ask about.
//
// GEOMETRY, NOT THE FILE. Carbon's svg wrapper carries xmlns and viewBox that
// say nothing about the shape, and our sprite rewrites both into <symbol>. What
// must match is the drawing: every geometry child in order, with its attributes
// sorted so attribute order cannot fail a comparison it has no business
// failing.
//
// THE SIZE IS PART OF THE IDENTITY. Carbon does not scale one path to four
// sizes — 16, 20, 24 and 32 are separately drawn, and arrow--up at 32 starts
// `M16 4` where at 16 it starts `M3.7 6.7`. A snapshot keyed by name alone
// would compare a glyph against a different drawing of the same idea and call
// it a mismatch. Keyed by name AND viewBox size, it compares like with like.
//
// Some icons have no size variants at all and live at svg/<name>.svg. They are
// not a special case to work around — they are simply where Carbon keeps a
// glyph it draws once, and the lookup tries the sized path first and falls back.
//
//   node tools/glyphs.mjs          write docs/carbon-glyphs.json
//   node tools/glyphs.mjs --check  exit 1 if the snapshot is out of date
//
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const SPRITE = 'assets/icons.svg';
const OUT = 'docs/carbon-glyphs.json';
const PKG = 'node_modules/@carbon/icons';

// The elements that DRAW. Anything else in an icon file — <title>, <defs>, a
// stray comment — describes it rather than draws it, and comparing those would
// fail on Carbon's own metadata churn.
const GEOMETRY = /<(path|circle|rect|polygon|polyline|ellipse|line)\b([^>]*)\/?>/g;

// Attributes sorted, whitespace collapsed: two files that draw the same shape
// must compare equal even when one writes `d` before `fill` and the other after.
export function geometry(svg) {
  const out = [];
  for (const [, tag, attrs] of svg.matchAll(GEOMETRY)) {
    const pairs = [...attrs.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)]
      .map(([, k, v]) => [k, v.replace(/\s+/g, ' ').trim()])
      .filter(([k]) => k !== 'xmlns')
      .sort(([a], [b]) => a.localeCompare(b));
    out.push(tag + '|' + pairs.map(([k, v]) => `${k}=${v}`).join(' '));
  }
  return out;
}

// [{ name, size, geometry }] for every symbol the sprite defines.
export function spriteSymbols(src = readFileSync(SPRITE, 'utf8')) {
  const out = [];
  for (const [, id, vb, body] of src.matchAll(
    /<symbol id="i-([^"]+)"[^>]*viewBox="([^"]+)"[^>]*>([\s\S]*?)<\/symbol>/g)) {
    const size = vb.trim().split(/\s+/)[2];   // "0 0 16 16" -> "16"
    out.push({ name: id, size, geometry: geometry(body) });
  }
  return out;
}

// Sized first, then the unsized glyph file. Returns null when Carbon has
// neither, which is a finding rather than a fallback — a name we invented.
function carbonGlyph(name, size) {
  for (const p of [`${PKG}/svg/${size}/${name}.svg`, `${PKG}/svg/${name}.svg`]) {
    if (existsSync(p)) return { path: p, geometry: geometry(readFileSync(p, 'utf8')) };
  }
  return null;
}

function build() {
  const glyphs = {};
  const absent = [];
  for (const { name, size } of spriteSymbols()) {
    const found = carbonGlyph(name, size);
    if (!found) { absent.push(`${name}@${size}`); continue; }
    glyphs[`${name}@${size}`] = { name, size, source: found.path, geometry: found.geometry };
  }
  return { glyphs, absent };
}

// RUN ONLY AS A COMMAND. check-glyphs imports geometry() and spriteSymbols()
// from here, and while this ran at import time that import REGENERATED the
// snapshot the gate then compared against — a check that rewrites its own
// reference can never fail. Caught on the gate's first run, when it printed this
// file's output before its own.
if (import.meta.url !== pathToFileURL(process.argv[1]).href) {
  // imported: exports only, no side effects
} else main();

function main() {
const { glyphs, absent } = build();
const snapshot = {
  _: 'Carbon\'s own drawing of every glyph assets/icons.svg claims, keyed name@size. '
    + 'Generated by tools/glyphs.mjs from @carbon/icons and committed so check-glyphs '
    + 'survives Phase 4, which removes node_modules/@carbon. Regenerate only when the '
    + 'sprite gains a symbol or @carbon/icons is upgraded — never to make a gate pass.',
  version: JSON.parse(readFileSync(`${PKG}/package.json`, 'utf8')).version,
  glyphs,
};

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  const fresh = JSON.stringify(snapshot, null, 2) + '\n';
  if (current !== fresh) {
    console.error('\n  docs/carbon-glyphs.json is out of date — run `node tools/glyphs.mjs`\n');
    process.exit(1);
  }
  console.log(`\n  glyph snapshot current · ${Object.keys(glyphs).length} glyphs\n`);
  process.exit(0);
}

writeFileSync(OUT, JSON.stringify(snapshot, null, 2) + '\n');
console.log(`\n  ${OUT} — ${Object.keys(glyphs).length} glyphs from @carbon/icons ${snapshot.version}`);
if (absent.length) console.log(`  ${absent.length} sprite symbols Carbon has no file for: ${absent.join(', ')}`);
console.log();
}
