/* ==========================================================================
   rux-ds — BUILDER                                    roadmap §4.12, creator 3
   --------------------------------------------------------------------------
   The page builder's behaviour, for builder.html (generated by
   tools/build-builder.mjs). Hand-written, and deliberately NOT in js/:
   tools/lib/stats.mjs counts js/ as the published module set, and every
   app links it from rux-ds directly. This file belongs to one page in this
   repository.

   WHAT IT DOES, this stage: fetches builder/blocks.json, offers the ten
   templates and the answers new-project.sh asks, and keeps ONE PAGE MODEL
   PER TEMPLATE (builder/page.mjs) — the template's own blocks to begin with,
   then whatever the reader adds from the catalogue, moves or removes. The
   model is composed into the page by composePage, which puts every instance
   through instanceOf so a block placed twice keeps its labels bound to its
   own radios, and the preview shows the result in an iframe at a chosen
   width. Every block on the page is offered by label, its editable text is
   listed, and an edit is written back through applyTextEdits, keyed by the
   INSTANCE (`id@n`) so two copies edit apart. Every one of those actions can
   be UNDONE, and the whole session survives a reload as a draft.

   ONE HISTORY, AND ONE ENTRY PER ACTION. builder/session.mjs holds the
   history and the draft; this file decides what an action IS. Every user
   action goes through change() or typed(), which snapshot before, run the
   whole action — Remove touches both the edits and the model, and that is
   ONE entry, not two — and record only if something actually moved. The
   low-level setters below (setEdit, dropEdits, setPage) never touch history
   themselves, which is what keeps an action atomic. Navigation records
   nothing: switching template, slot, block, catalogue or width is not a
   change, so undo and redo instead SELECT the template the action happened
   on, and say so in the button's name.

   THE PREVIEW IS A BLOB URL, not srcdoc. A srcdoc document inherits the
   parent's base URL, so `href="#main-content"` — every template's skip link
   — can resolve to builder.html#main-content and navigate the frame away. A
   blob: document created here has this origin and a URL of its own, so
   fragments stay put and css/, js/ and assets/ load by absolute URL. The
   URL is revoked once the frame has loaded it.

   NOTHING HERE CONSTRUCTS rux-- MARKUP. The chrome is in the generated page,
   where check-classes reads it; this file only fills <select>s, toggles
   aria-pressed and disabled, writes an iframe's src and size, and CLONES the
   four <template>s builder.html ships — a text field, the no-fields line,
   and the two notices. Real component markup is authored in the generator
   and cloned here, never assembled out of class-name strings.

   AND IT CAN BE TAKEN AWAY. Two delivery paths, no third: download the page
   for a project that exists, or copy the whole <main> to replace one; or, for
   a project that does not exist yet, copy the exact new-project.sh command
   built from the answers. THE SCRIPT STAYS THE ONE PROJECT CREATOR — the
   builder writes a page, never a project — and tools/check-parity.mjs holds
   exportPage to the script's own page-writing lines, run per template.

   TWO MODES, ONE PAGE (stage 12). The guided mode shows the five sections
   one at a time behind a vertical progress indicator, with Back and Next;
   the free mode shows all five at once. Both share every control, the
   draft, the model and the history. A mode and a step are WHERE THE READER
   IS STANDING, like the template and the width: not in history, not in the
   draft, remembered per browser under a second key so a reload lands on the
   same step and the draft's validation table does not move. Two controls
   per state where the guided one has to say more — a purpose radio group
   beside the template select, an outline beside the block select — and both
   write the same state through the same handler.

   NOT YET: escaping the answers as HTML — neither this nor the script does,
   and both say so rather than pretending otherwise.
   ========================================================================== */
import { compose, previewPage, exportPage, bodyOnly, textFieldsOf, linksOf, variantsOf, applyTextEdits, integrity } from './rewrites.mjs';
import { newPage, add, move, remove, unitOf, entriesOf, composePage } from './page.mjs';
import { matchesContainer, offerFor, frameNeedsOf, frameNeedsMissing, suggestionsFor, recommendationFor } from './placement.mjs';
import { emptyHistory, pushed, undone, redone, runKey, sameRun,
         toDraft, fromDraft, agoOf, copy, identical } from './session.mjs';

const ROOT = new URL('.', location.href).href;
const DRAFT_KEY = 'rux.draft';
// Where the reader is standing: { mode, step, template }. A second key, not a field of
// the draft, so the draft's validation table is untouched and a view written
// by a future version cannot make a draft unopenable.
const VIEW_KEY = 'rux.builder.view';
const STEPS = 5;
const SAVE_MS = 500;
const $ = s => document.querySelector(s);
const frame = $('#bld-frame'), wrap = $('#bld-frame-wrap'), status = $('#bld-status'), integrityLine = $('#bld-integrity');

// `pages` holds one model per template, made on first use from the manifest
// and kept when the reader switches away and back. `edits` is namespaced per
// template, then per ENTRY KEY (`id@n`, so two instances edit apart), then by
// FIELD INDEX into that block's original html: { template: { key: { 0: 'text' } } }.
// It is pruned as it goes — typing a value back to the original deletes the
// index, an empty map is deleted outright, and removing a block drops its
// edits — so the count in the status line and Reset's disabled state cannot
// drift from it.
//
// THE SNAPSHOT IS `pages`, `edits` AND THE FIVE ANSWERS, and nothing else.
// `template`, `block`, `slot`, `catalogue` and `width` are where the reader
// is standing and what they are looking through, not what they have made.
const ANSWERS = ['theme', 'grid', 'prefix', 'name', 'title', 'page'];
const FRESH = { theme: 'white', grid: 'capped', prefix: '', name: '', title: '', page: '' };
const state = { template: 'app-shell', block: '', slot: '', catalogue: '', rest: '', width: 'fit', mode: 'guided', step: 1, ...FRESH, edits: {}, links: {}, variants: {}, pages: {} };
let manifest = null;
// The guide map. Absent is not fatal: the catalogue still splits by evidence,
// which is derived, and only the purpose line and the suggestions go missing.
let guide = null;
let history = emptyHistory();
let run = null;                  // the typing run in progress, or null
let saveTimer = null, saveBlocked = false, unopened = false;
const templates = new Map();     // name → source text
const blocks = new Map();        // id → manifest block

const answers = () => {
  const prefix = state.prefix.trim() || 'Rux';
  const name = state.name.trim() || 'DS';
  return { theme: state.theme, grid: state.grid, prefix, name, title: state.title.trim() || `${prefix} ${name}` };
};

async function fetchText(url) {
  const r = await fetch(url, { cache: 'no-store' });
  if (!r.ok) throw new Error(`${url}: ${r.status}`);
  return r.text();
}

async function source(name) {
  if (!templates.has(name)) templates.set(name, await fetchText(`templates/${name}.html`));
  return templates.get(name);
}

const templateOf = name => manifest.templates.find(x => x.name === name);
// The template's own blocks by name, for the round trip on its own slots.
const blocksOf = t => Object.fromEntries(manifest.blocks.filter(b => b.source === t.path).map(b => [b.name, b]));
const pageOf = () => (state.pages[state.template] ??= newPage(manifest, state.template));
const setPage = p => { state.pages[state.template] = p; };
const entries = () => entriesOf(pageOf(), templateOf(state.template));
const entryOf = key => entries().find(e => e.key === key);
// The saved edits for one entry, or an empty map. Never creates the maps.
const editsFor = (tpl, key) => (state.edits[tpl] ?? {})[key] ?? {};
// The same, for link targets. TWO STORES, ONE SHAPE, and deliberately not one
// map with mixed keys: a text edit indexes textFieldsOf and a link edit
// indexes linksOf, so sharing an index space would make either one shift the
// other — and a draft written before links existed would silently retarget.
const linksFor = (tpl, key) => (state.links[tpl] ?? {})[key] ?? {};
// And the same for variants — button size per group, table density. THREE
// STORES, ONE SHAPE. Each keys by an ORDINAL into a list derived from the
// block's markup: a field index, a link index, a group index. rux's review of
// stage 9 caught the alternative — keying a group by its byte offset — which
// breaks the moment an earlier edit changes length.
const variantsFor = (tpl, key) => (state.variants[tpl] ?? {})[key] ?? {};
// A block is native when it is the template's own, at instance 1.
const isNative = (e, t) => e.n === 1 && blocks.get(e.id).source === t.path;
const short = cls => (cls ?? '').split(/\s+/).filter(Boolean).map(c => c.replace(/^rux--/, '')).join(' ');
const labelOf = key => blocks.get(entryOf(key)?.id)?.label ?? 'block';

// ── HISTORY ────────────────────────────────────────────────────────────────

// A COPY, ALWAYS. Handing back live references made change() compare an
// object with itself — fn() mutates state.pages in place, so `before` moved
// with it, every action looked like a no-op and the first browser run
// recorded an empty history after add, edit and remove. Copying here makes
// that mistake unavailable to every caller rather than fixing it at one.
const snapshot = () => copy({
  pages: state.pages,
  edits: state.edits,
  links: state.links,
  variants: state.variants,
  answers: Object.fromEntries(ANSWERS.map(k => [k, state[k]])),
});

// Put a restored snapshot back, controls included. The six answers are DOM
// state as well as data, so they are written back here rather than left for
// a render to notice.
function applySnapshot(s) {
  state.pages = copy(s.pages);
  state.edits = copy(s.edits);
  // `?? {}` because a draft written before stage 8 has no links at all, and
  // an undo entry from earlier in this same session does not either.
  state.links = copy(s.links ?? {});
  state.variants = copy(s.variants ?? {});
  for (const k of ANSWERS) state[k] = s.answers[k] ?? FRESH[k];
  for (const r of document.querySelectorAll('input[name="bld-theme"]')) r.checked = r.value === state.theme;
  for (const r of document.querySelectorAll('input[name="bld-grid"]')) r.checked = r.value === state.grid;
  for (const [id, key] of FIELDS) $(`#${id}`).value = state[key];
}

const FIELDS = [['bld-prefix', 'prefix'], ['bld-name', 'name'], ['bld-title', 'title'], ['bld-page', 'page']];

const endRun = () => { run = null; };

// ONE ACTION, ONE ENTRY. Snapshot, run the whole thing, and record only if
// it moved: a move at the end of a slot, a Reset with nothing to reset and a
// field typed back to its original all call a setter and change nothing, and
// none of them is worth an entry the reader would have to press twice.
function change(label, fn) {
  const before = snapshot(), template = state.template;
  fn();
  if (identical(before, snapshot())) return false;
  history = pushed(history, before, label, template);
  endRun();
  syncHistory();
  saveSoon();
  return true;
}

// A keystroke. The FIRST of a run records the state before the run; the rest
// join it. Every boundary that ENDS a run is elsewhere — blur, navigation,
// any change(), undo, redo — because those are events, not values.
function typed(where, label, fn) {
  const key = runKey(state.template, where), now = Date.now();
  const before = snapshot(), template = state.template;
  fn();
  if (identical(before, snapshot())) return;
  if (!sameRun(run, key, now)) history = pushed(history, before, label, template);
  run = { key, at: now };
  syncHistory();
  saveSoon();
}

function step(way) {
  const moved = way === 'undo' ? undone(history, snapshot()) : redone(history, snapshot());
  if (!moved) return;
  history = moved.history;
  endRun();
  applySnapshot(moved.state);
  // Reveal where it happened, in BOTH directions: the entry's template, not
  // the one the reader is standing on and not the snapshot's, either.
  state.template = moved.entry.template;
  $('#bld-template').value = state.template;
  fillSlots();
  fillPicker();
  render();
  syncHistory();
  saveSoon();
}

function syncHistory() {
  const u = $('#bld-undo'), r = $('#bld-redo');
  const last = history.past[history.past.length - 1], next = history.future[history.future.length - 1];
  u.disabled = !last;
  r.disabled = !next;
  u.setAttribute('aria-label', last ? `Undo ${last.label}` : 'Undo');
  r.setAttribute('aria-label', next ? `Redo ${next.label}` : 'Redo');
}

// ── THE DRAFT ──────────────────────────────────────────────────────────────

// Every read and write is wrapped: a private window, a full quota or a store
// the browser has blocked must not break the page.
function writeDraft() {
  if (saveBlocked || unopened) return;
  saveTimer = null;
  try {
    localStorage.setItem(DRAFT_KEY, JSON.stringify(toDraft(snapshot(), id => blocks.get(id)?.html)));
  } catch (e) {
    // NOT THE STATUS LINE. render() rewrites it on every keystroke and would
    // erase this within the second.
    saveBlocked = true;
    alertNotice('Your work is not being saved',
      `The browser refused to store this draft (${e.name || 'error'}), so a reload will lose it. Export the page when you are done.`);
  }
}

const saveSoon = () => {
  if (saveBlocked || unopened) return;
  clearTimeout(saveTimer);
  saveTimer = setTimeout(writeDraft, SAVE_MS);
};

const flushSave = () => { if (saveTimer !== null) { clearTimeout(saveTimer); writeDraft(); } };
const cancelSave = () => { clearTimeout(saveTimer); saveTimer = null; };
const clearDraft = () => { try { localStorage.removeItem(DRAFT_KEY); } catch { /* nothing to do */ } };

// Cloned, never constructed: the two notices are real component markup and
// live in builder.html where check-classes reads them.
//
// TWO REGIONS, AND THAT IS WHY THIS TAKES A BOX. Showing a notice CLEARS its
// container, so routing export feedback through #bld-notice would delete the
// "saved draft was left unopened" warning AND ITS DISCARD BUTTON while
// `unopened` still blocks every save — leaving the reader no way to reach the
// one control that restores saving, and no sign anything was wrong. The same
// applies to the save-failure alert. So #bld-notice is the persistent region,
// owned by the draft and the save, and #bld-export-notice is the transient one
// beside the buttons that caused it. An export never touches the first.
function showNotice(templateId, title, subtitle, action, onAction, into = '#bld-notice') {
  const box = $(into);
  box.textContent = '';
  const node = $(`#${templateId}`).content.cloneNode(true);
  node.querySelector('.rux--actionable-notification__title').textContent = title;
  node.querySelector('.rux--actionable-notification__subtitle').textContent = subtitle;
  const button = node.querySelector('.rux--actionable-notification__action-button');
  if (button) {
    if (action) { button.textContent = action; button.addEventListener('click', onAction); }
    else button.remove();
  }
  box.append(node);
}

const alertNotice = (title, subtitle) => showNotice('bld-alert-template', title, subtitle, null, null);
const exportNotice = (title, subtitle) => showNotice('bld-notice-template', title, subtitle, null, null, '#bld-export-notice');
const exportAlert = (title, subtitle) => showNotice('bld-alert-template', title, subtitle, null, null, '#bld-export-notice');

// On load, before the first render. A draft is opened only when session.mjs
// can establish that it still fits this manifest; anything else is left
// exactly where it is until Discard or Start over explicitly removes it.
function openDraft() {
  let raw = null;
  try { raw = localStorage.getItem(DRAFT_KEY); } catch { return; }
  if (!raw) return;
  const read = fromDraft(raw, manifest);
  if (!read.ok) {
    unopened = true;   // and nothing is saved over it while it sits there
    showNotice('bld-notice-template', 'A saved draft was left unopened',
      `${read.reason}. Nothing has been changed or removed. Discard it to start saving again.`,
      'Discard', () => { unopened = false; clearDraft(); $('#bld-notice').textContent = ''; saveSoon(); });
    return;
  }
  applySnapshot(read.state);
  if (state.pages[state.template] === undefined) {
    const first = Object.keys(read.state.pages)[0];
    if (first) state.template = first;
  }
  showNotice('bld-notice-template', 'Picked up where you left off',
    `This draft was saved ${agoOf(read.savedAt)}. Start over to clear it and begin again.`,
    'Start over', startOver);
}

function startOver() {
  change('start over', () => {
    state.pages = {};
    state.edits = {};
    state.links = {};
    state.variants = {};
    for (const k of ANSWERS) state[k] = FRESH[k];
  });
  applySnapshot(snapshot());          // write the cleared answers into the controls
  // The key goes, and nothing rewrites it until the reader changes something.
  cancelSave();
  clearDraft();
  unopened = false;                 // Start over also discards an incompatible draft
  $('#bld-notice').textContent = '';
  fillSlots();
  fillCatalogue();
  fillPicker();
  fillPurpose();
  setMode('guided', false);
  setStep(1);
  render();
}

// ── WHERE THE READER IS STANDING ───────────────────────────────────────────
//
// Read and written like the draft, inside try/catch: a blocked store must not
// break the page, and a view that does not parse is a fresh page.
function readView() {
  try {
    const v = JSON.parse(localStorage.getItem(VIEW_KEY) ?? 'null');
    if (v && (v.mode === 'guided' || v.mode === 'free') && Number.isInteger(v.step) && v.step >= 1 && v.step <= STEPS) return v;
  } catch { /* a fresh page */ }
  return null;
}
// The template rides along: it is not in the draft either (session.mjs, "the
// selected template is NOT in the snapshot"), and a reload that opened the
// draft on a different template than the one being edited read as a loss.
const writeView = () => { try { localStorage.setItem(VIEW_KEY, JSON.stringify({ mode: state.mode, step: state.step, template: state.template })); } catch { /* nothing to do */ } };

// EVERYTHING A MODE HIDES IS A PLAIN WRAPPER, never a component root: see
// build-builder.mjs's header for why `hidden` on a flex component loses.
function setMode(mode, focus = true) {
  state.mode = mode;
  const guided = mode === 'guided';
  for (const b of document.querySelectorAll('[data-mode]')) b.setAttribute('aria-pressed', String(b.dataset.mode === mode));
  $('#bld-stepper').hidden = !guided;
  $('#bld-nav').hidden = !guided;
  $('#bld-purpose').hidden = !guided;
  $('#bld-template-free').hidden = guided;
  $('#bld-outline').hidden = !guided;
  $('#bld-picker-free').hidden = guided;
  $('#bld-keep-line').hidden = !guided;
  for (const sec of document.querySelectorAll('.bld-step')) sec.hidden = guided && Number(sec.dataset.step) !== state.step;
  writeView();
  if (focus) $(`#bld-h-${state.step}`).focus();
}

// The stepper, Back, Next, and which section is shown. Steps before the
// current one read complete, the current one current, the rest not started —
// and every one is clickable, because the reader can go back and forth
// without loss: nothing here is a change.
const STEP_GLYPH = { complete: 'i-checkmark--outline', current: 'i-incomplete', incomplete: 'i-circle-dash' };
const STEP_TEXT = { complete: 'Complete', current: 'Current', incomplete: 'Not started' };
function setStep(n, focus = true) {
  state.step = Math.min(STEPS, Math.max(1, n));
  for (const li of document.querySelectorAll('#bld-stepper .rux--progress-step')) {
    const i = Number(li.querySelector('[data-step]').dataset.step);
    const st = i < state.step ? 'complete' : i === state.step ? 'current' : 'incomplete';
    li.classList.remove('rux--progress-step--complete', 'rux--progress-step--current', 'rux--progress-step--incomplete');
    li.classList.add(`rux--progress-step--${st}`);
    li.querySelector('use').setAttribute('href', `#${STEP_GLYPH[st]}`);
    li.querySelector('.rux--assistive-text').textContent = STEP_TEXT[st];
    li.querySelector('[data-step]').setAttribute('aria-current', i === state.step ? 'step' : 'false');
  }
  $('#bld-back').disabled = state.step === 1;
  $('#bld-next').disabled = state.step === STEPS;
  if (state.mode === 'guided') for (const sec of document.querySelectorAll('.bld-step')) sec.hidden = Number(sec.dataset.step) !== state.step;
  writeView();
  // Focus lands on the step's heading, so Tab continues from the top of the
  // step rather than from wherever the pressed button was.
  if (focus) $(`#bld-h-${state.step}`).focus();
}

// One handler for the template, whichever control chose it.
function selectTemplate(name) {
  endRun();
  state.template = name;
  $('#bld-template').value = name;
  const r = document.querySelector(`input[name="bld-purpose"][value="${CSS.escape(name)}"]`);
  if (r) r.checked = true;
  fillSlots();
  fillCatalogue();
  fillPicker();
  render();
}
const fillPurpose = () => { const r = document.querySelector(`input[name="bld-purpose"][value="${CSS.escape(state.template)}"]`); if (r) r.checked = true; };

// THE OUTLINE: one row per UNIT — a leader and the followers that ride with
// it — in document order, cloned from the page's own contained-list item.
// The row for the unit the panel is editing carries aria-current and says
// so, because a clickable item has no selected state of its own to show.
function fillOutline() {
  const list = $('#bld-outline-list');
  const had = list.contains(document.activeElement);
  list.textContent = '';
  const t = templateOf(state.template);
  const es = entries();
  const seen = new Set();
  let current = null;
  for (const e of es) {
    if (seen.has(e.key)) continue;
    const u = unitOf(pageOf(), e.key);
    for (const k of u.keys) seen.add(k);
    const row = $('#bld-outline-item-template').content.cloneNode(true);
    const btn = row.querySelector('button');
    const names = u.keys.map(k => { const x = entryOf(k); const b = blocks.get(x.id); return `${b.label}${x.n > 1 ? ` (${x.n})` : ''}`; });
    const isCurrent = u.keys.includes(state.block);
    btn.textContent = `${t.slots.length > 1 ? `${e.slot} · ` : ''}${names[0]}${names.length > 1 ? ` · with ${names.slice(1).join(', ')}` : ''}${isCurrent ? ' · editing' : ''}`;
    btn.setAttribute('aria-current', isCurrent ? 'true' : 'false');
    btn.dataset.key = u.keys[0];
    btn.addEventListener('click', () => { endRun(); state.block = u.keys[0]; $('#bld-block').value = state.block; showBlock(); });
    if (isCurrent) current = btn;
    list.append(row);
  }
  if (!es.length) {
    const row = $('#bld-outline-item-template').content.cloneNode(true);
    const btn = row.querySelector('button');
    btn.textContent = 'Nothing on the page yet — add a section at the next step.';
    btn.disabled = true;
    list.append(row);
  }
  // A rebuild replaced the row that had focus; put it back on the current one.
  if (had && current) current.focus();
}

// "Keep recommended settings", or "Keep attested settings" while the map's
// recommendation for a group is unreviewed: an unreviewed draft never speaks
// as a recommendation (stage 11). One button for the unit: it puts every
// variant group of the selected block at what the map recommends, which is
// as-attested for every group today, so it drops the overrides.
function targetsFor(key) {
  const e = entryOf(key);
  if (!e) return [];
  const groups = variantsOf(blocks.get(e.id).html);
  return groups.map((g, i) => {
    const rec = recommendationFor(guide, e.id, i);
    const reviewed = rec?.reviewed === true;
    const value = rec && rec.recommended !== 'as-attested' && g.values.includes(rec.recommended) ? rec.recommended : '';
    return { i, value, reviewed };
  });
}
function syncKeep() {
  const wrap = $('#bld-keep-wrap'), btn = $('#bld-keep'), note = $('#bld-keep-note');
  const targets = targetsFor(state.block);
  wrap.hidden = !targets.length;
  if (!targets.length) return;
  const saved = variantsFor(state.template, state.block);
  const allReviewed = targets.every(t => t.reviewed);
  const atTarget = targets.every(t => (Object.hasOwn(saved, t.i) ? saved[t.i] : '') === t.value);
  btn.textContent = allReviewed ? 'Keep recommended settings' : 'Keep attested settings';
  btn.disabled = atTarget;
  note.textContent = allReviewed
    ? (atTarget ? 'Sizes and densities are at what the map recommends for this block.' : 'Puts every size and density here back to what the map recommends.')
    : (atTarget ? 'Sizes and densities are as this block ships them; the map has no reviewed recommendation beyond that.' : 'Puts every size and density here back to what the block ships, which is all the map recommends until its entry is reviewed.');
}
function keepSettings() {
  const key = state.block;
  const targets = targetsFor(key);
  if (!targets.length) return;
  change(`keep settings in ${labelOf(key)}`, () => {
    for (const t of targets) { if (t.value) setVariant(key, t.i, t.value, ''); else dropOne(state.variants, key, t.i); }
    syncReset();
  });
  showBlock();
  $('#bld-keep').focus();
  later();
}

// ── THE PAGE ───────────────────────────────────────────────────────────────

// The composed page and its two readings. `roundTrip` is deliberately
// measured on the template's OWN slot records, unedited and unarranged — that
// check asks whether the builder can reproduce the template it was given,
// and nothing the reader does is supposed to make it fail, so letting the
// model change the answer would destroy the only thing it says. `integrity`
// is the opposite: it reads the page the reader actually built.
async function composed() {
  const src = await source(state.template);
  // The frame note reads the destination template's own ids, and the source is
  // fetched lazily, so the first render is where it can first be right.
  frameNote();
  const t = templateOf(state.template);
  const page = composePage(src, t, pageOf(), manifest, state.edits[state.template] ?? {}, state.links[state.template] ?? {}, state.variants[state.template] ?? {});
  return { page, roundTrip: compose(src, t.slots, blocksOf(t)) === src, integrity: integrity(page) };
}

// `field.raw` is a slice of the original HTML SOURCE, so real text carrying an
// ampersand is stored as the literal bytes `&amp;`. Showing that verbatim in a
// textarea would display the escape sequence itself, and submitting it back
// unchanged would escape it a second time into `&amp;amp;`. One-way and for
// display only: the write path only ever sees plain decoded text.
function decodeText(raw) {
  const probe = document.createElement('textarea');
  probe.innerHTML = raw;
  return probe.value;
}

// The field rows for one entry. `html` MUST be the block's ORIGINAL html from
// the manifest, never an instanced or edited derivative: every recorded index,
// and the original each edit is compared against to decide whether to prune
// it, is an offset into that exact string. Instancing touches no text, so the
// indices hold on the page (proved in stage 4). Saved edits are laid over it
// for display only.
// WHAT A FIELD IS CALLED. Every entry is a class this repository already ships
// and the count it occurs at, taken from the 241 fields in the catalogue rather
// than imagined: the tag alone is useless because div, p and span hold 127 of
// them, and <th> holds none at all — a column header wraps its text in a div.
// The FIRST match down this list wins, so the specific sits above the general.
// Anything unlisted falls back to the tag, which is what the panel said before
// this stage; a wrong name is worse than a plain one.
const ROLES = [
  [/rux--form__helper-text|rux--form-requirement/, 'Helper text'],
  [/rux--checkbox-label-text/, 'Checkbox'],
  [/rux--radio-button__label-text/, 'Radio label'],
  [/rux--toggle__label-text/, 'Toggle label'],
  [/rux--table-header-label/, 'Column header'],
  [/rux--structured-list-th/, 'Column header'],
  [/rux--structured-list-td/, 'Cell'],
  [/rux--tabs__nav-item-label/, 'Tab'],
  [/rux--accordion__title/, 'Section title'],
  [/rux--tag__label/, 'Status'],
  [/rux--inline-notification__title/, 'Notification title'],
  [/rux--inline-notification__subtitle/, 'Notification text'],
  [/rux--list-box__menu-item__option/, 'Option'],
  [/rux--select-option/, 'Option'],
  [/rux--contained-list__label/, 'List label'],
  [/rux--progress-label/, 'Step'],
  [/rux--progress-optional/, 'Step note'],
  [/rux--pagination__/, 'Pagination text'],
  [/rux--full-page-error__label/, 'Error code'],
  [/rux--full-page-error__description/, 'Error text'],
  [/rux--data-table-header__title/, 'Table title'],
  [/rux--data-table-header__description/, 'Table description'],
  [/rux--inline-loading__text/, 'Loading text'],
  [/rux--link/, 'Link'],
  [/rux--btn/, 'Button'],
  [/rux--label/, 'Label'],
  [/rux--list__item/, 'Item'],
];
const BY_TAG = { h1: 'Heading', h2: 'Heading', h3: 'Heading', p: 'Paragraph', td: 'Cell', li: 'Item', a: 'Link', button: 'Button', label: 'Label', legend: 'Legend', option: 'Option' };

// A legend is a <legend class="rux--label">, so it must be read before the
// generic label rule; the tag decides that one, not the class.
function roleOf(f) {
  if (f.name === 'legend') return 'Legend';
  for (const [re, name] of ROLES) if (re.test(f.context.cls)) return name;
  if (BY_TAG[f.name]) return BY_TAG[f.name];
  // AN UNCLASSED WRAPPER TAKES ITS NAME FROM WHAT HOLDS IT. The activity list
  // on dashboard-page is a bare <div> inside li.rux--list__item, and the leaf
  // alone said nothing — it read "Text 21 of 25". The nearest ancestor that
  // has a role does, so ask it before falling back to a position.
  for (const a of [...f.context.chain].reverse()) {
    for (const [re, name] of ROLES) if (re.test(a.cls)) return name;
  }
  return null;
}

// The group a field belongs to, as a stable identity plus a name. `at` is an
// ancestor's content offset, unique inside the block, so two fields under the
// same form item share it by construction rather than by matching text.
const GROUPS = [
  [/rux--form-item/, 'Form item'],
  [/rux--btn-set/, 'Actions'],
  [/rux--table-header-row/, 'Column headers'],
  [/rux--structured-list-row/, 'Row'],
  [/rux--tab-panel/, 'Tab panel'],
  [/rux--contained-list/, 'List'],
  [/rux--accordion__item/, 'Section'],
];
// The NEAREST enclosing unit wins, so the walk is inside out. A fieldset is
// matched by its TAG, not a class: the two in form-page carry
// rux--radio-button-group and rux--checkbox-group and share no class between
// them, and reading it off the class list is what left "Notify me when"
// heading-less on the first run.
function groupOf(f) {
  const inside = [...f.context.chain].reverse();
  // A FIELDSET BEATS ANYTHING NESTED IN IT, and that is not a preference — a
  // fieldset is by definition the set of controls its legend names, so it IS
  // the group. Nearest-unit alone splits one apart: form-page's two checkboxes
  // each sit in their own rux--form-item inside the fieldset while its two
  // radios do not, so "Notify me when" lost its legend to one group and its
  // options to two others, and rendered with no heading at all. Measured on
  // the block, not reasoned about.
  const fs = inside.find(a => a.tag === 'fieldset');
  if (fs) return { at: fs.at, kind: 'Fieldset' };
  for (const a of inside) {
    // The <tr>s carry no class at all, here or in any captured table, so the
    // head is told from the body by its <thead> — without which the first body
    // row read "Row 2", the header row having silently taken Row 1.
    if (a.tag === 'tr') return { at: a.at, kind: inside.some(x => x.tag === 'thead') ? 'Column headers' : 'Row' };
    for (const [re, kind] of GROUPS) if (re.test(a.cls)) return { at: a.at, kind };
  }
  return null;
}

// The field rows for one entry. `html` MUST be the block's ORIGINAL html from
// the manifest, never an instanced or edited derivative: every recorded index,
// and the original each edit is compared against to decide whether to prune
// it, is an offset into that exact string. Instancing touches no text, so the
// indices hold on the page (proved in stage 4). Saved edits are laid over it
// for display only.
function renderFieldPanel(key, html) {
  const box = $('#bld-fields');
  box.textContent = '';
  const fields = textFieldsOf(html);
  const links = linksOf(html);
  if (!fields.length && !links.length) {
    box.append($('#bld-no-fields-template').content.cloneNode(true));
    return;
  }
  const saved = editsFor(state.template, key);
  const savedLinks = linksFor(state.template, key);
  const valueOf = (i, original) => Object.hasOwn(saved, i) ? saved[i] : original;

  // Group first, then name, because a group's heading is one of its own
  // fields: the label or legend inside it. Ungrouped fields keep their order
  // and stand alone, so a block with no form items reads as it did before.
  const groups = new Map();
  const order = [];
  fields.forEach((f, i) => {
    const g = groupOf(f);
    const id = g ? g.at : `solo-${i}`;
    if (!groups.has(id)) { groups.set(id, { g, rows: [] }); order.push(id); }
    groups.get(id).rows.push({ f, i });
  });

  // A FALLBACK NAME IS NUMBERED ONLY WHEN IT HAS TO BE. The first run read
  // "Actions 7" — the seventh div among its siblings, a number that means
  // nothing to a reader. So unnamed groups are numbered by their order among
  // groups of the SAME KIND, and a kind that occurs once stays bare: "Actions",
  // but "Row 1" … "Row 4".
  const kinds = new Map();
  for (const id of order) {
    const g = groups.get(id).g;
    if (g) kinds.set(g.kind, (kinds.get(g.kind) ?? 0) + 1);
  }
  const seen = new Map();
  for (const id of order) {
    const g = groups.get(id).g;
    if (!g) continue;
    const n = (seen.get(g.kind) ?? 0) + 1;
    seen.set(g.kind, n);
    groups.get(id).fallback = kinds.get(g.kind) > 1 ? `${g.kind} ${n}` : g.kind;
  }

  for (const id of order) {
    const { g, rows, fallback } = groups.get(id);
    let rename = null, namingIndex = -1;
    // ONE FIELD, NO HEADING. A heading over a single unlabelled row is chrome
    // for its own sake, and it pushes the eighteen-row panel longer still.
    if (g && rows.length > 1) {
      const head = $('#bld-group-template').content.cloneNode(true);
      const h = head.querySelector('h3');
      // The heading is the group's own label or legend, and it shows the
      // EDITED text: rename Email to Work email and the panel must agree with
      // the preview. An edit may be the empty string — clearing a label is a
      // legal edit — so a blank one falls back to the structural name, and the
      // group's accessible name is never empty.
      // A GROUP IS NAMED BY WHICHEVER OF ITS OWN FIELDS NAMES IT — a legend, a
      // label, or an accordion's title, which is that section's label in all
      // but spelling. Without the last one the detail page's sections read
      // "Section 1" and "Section 2" above rows that already said Environment
      // and Networking.
      const NAMES = new Set(['Legend', 'Label', 'Section title', 'Table title']);
      const naming = rows.find(r => NAMES.has(roleOf(r.f)));
      const named = naming ? valueOf(naming.i, decodeText(naming.f.raw)).trim() : '';
      const wrap = head.querySelector('[role="group"]');
      // LIVE, not only on re-render. The panel is not rebuilt while typing —
      // that would take the caret with it — so the naming row updates its own
      // heading as it goes, or the panel keeps saying Email while the preview
      // says Work email. A blank edit is legal, so the fallback is applied
      // here too and the accessible name is never empty.
      rename = v => {
        h.textContent = (v ?? '').trim() || fallback;
        if (wrap) wrap.setAttribute('aria-label', h.textContent);
      };
      rename(named);
      namingIndex = naming ? naming.i : -1;
      box.append(head);
    }
    for (const { f, i } of rows) {
      const original = decodeText(f.raw);
      const role = roleOf(f);
      const same = rows.filter(r => roleOf(r.f) === role);
      const name = role
        ? (same.length > 1 ? `${role} ${same.findIndex(r => r.i === i) + 1}` : role)
        : `Text ${i + 1} of ${fields.length}`;
      box.append(fieldRow({
        key, i, name,
        hint: role ? null : `In <${f.name}>`,
        original,
        value: valueOf(i, original),
        store: state.edits,
        set: (v) => setEdit(key, i, v, original),
        runKey: `${key}#${i}`,
        label: `edit text in ${labelOf(key)}`,
        rename: i === namingIndex ? rename : null,
      }));
    }
  }

  // Variants before the link rows: they are the block's SHAPE rather than its
  // words, and a reader scanning for "how big are these buttons" should not
  // have to pass every field to find it. Keyed by GROUP INDEX, never by the
  // group's offset — see variantsFor.
  const savedVariants = variantsFor(state.template, key);
  const variantGroups = variantsOf(html);
  if (variantGroups.length) {
    const head = $('#bld-group-template').content.cloneNode(true);
    head.querySelector('h3').textContent = 'Size and density';
    const w = head.querySelector('[role="group"]');
    if (w) w.setAttribute('aria-label', 'Size and density');
    box.append(head);
  }
  variantGroups.forEach((g, i) => {
    const values = g.values.map(v => [v, VALUE_WORDS[v] ?? v]);
    box.append(variantRow({
      key, i, group: g, values,
      value: Object.hasOwn(savedVariants, i) ? savedVariants[i] : '',
      original: g.current,
    }));
  });

  // Link targets last, and only where there are any. A fragment href INTO
  // the block is a control relation instanceOf owns and linksOf never offers;
  // one pointing outside the block is a destination like any other.
  links.forEach((l, i) => {
    box.append(fieldRow({
      key, i, name: l.text ? `Link destination — ${l.text}` : 'Link destination',
      hint: null,
      original: decodeText(l.value),
      value: Object.hasOwn(savedLinks, i) ? savedLinks[i] : decodeText(l.value),
      store: state.links,
      set: (v) => setLink(key, i, v, decodeText(l.value)),
      runKey: `${key}$${i}`,          // $ not #, so a link run never joins a text run
      label: `edit a link in ${labelOf(key)}`,
      link: true,
    }));
  });
}

// WHAT A VARIANT GROUP IS CALLED. The module reports structure; these are the
// words, the same split stage 8 uses. `where` is btn-set, toolbar, lone or
// table.
const GROUP_NAME = { 'btn-set': 'Button set', toolbar: 'Toolbar buttons', lone: 'Button', table: 'Table rows' };
// THE WORDS ONLY. Which values a group offers comes from the group itself --
// variantsOf returns `values` -- because until 2026-09-05 this file carried a
// second copy of the list that rewrites.mjs already held, and stage 11's
// validator would have made a third. rux's review: one shared source. A value
// with no word here shows its own key rather than disappearing, so adding one
// to the matrix cannot silently drop it from the select.
const VALUE_WORDS = { xs: 'Extra small', sm: 'Small', md: 'Medium', lg: 'Large', xl: 'Extra large' };

// One variant row: a select, "as attested" first with the size the block ships
// named on it, then the five values. Choosing the attested value again is not
// the same as leaving it alone -- picking Large WRITES rux--layout--size-lg,
// which a bare button does not carry, and that is rux's call: the export says
// what it is rather than leaning on a default.
function variantRow({ key, i, group, values, value, original }) {
  const row = $('#bld-variant-template').content.cloneNode(true);
  const id = `bld-variant-${i}`;
  const label = row.querySelector('label'), select = row.querySelector('select');
  const named = values.find(([v]) => v === original)?.[1] ?? original;
  label.setAttribute('for', id);
  label.textContent = `${GROUP_NAME[group.where] ?? 'Group'}${group.kind === 'buttons' && group.targets.length > 1 ? ` (${group.targets.length})` : ''}`;
  select.id = id;
  select.append(option('', `As attested — ${String(named).toLowerCase()}`));
  for (const [v, text] of values) select.append(option(v, text));
  select.value = value;
  const help = row.querySelector('.rux--form__helper-text');
  const reset = row.querySelector('button');
  const sync = () => {
    const edited = Object.hasOwn((state.variants[state.template] ?? {})[key] ?? {}, i);
    help.textContent = edited ? `as attested: ${String(named).toLowerCase()}` : '';
    help.hidden = !help.textContent;
    reset.hidden = !edited;
  };
  sync();
  select.addEventListener('change', () => {
    endRun();
    change(`set ${(GROUP_NAME[group.where] ?? 'group').toLowerCase()} in ${labelOf(key)}`,
      () => setVariant(key, i, select.value, ''));
    sync();
    syncKeep();          // the Keep button reads the same store
    later();
  });
  reset.addEventListener('click', () => {
    change(`reset one group in ${labelOf(key)}`, () => { dropOne(state.variants, key, i); });
    select.value = '';
    sync();
    syncKeep();
    select.focus();
    later();
  });
  return row;
}

// One row: its name, its value, the original beside it while they differ, and
// a reset that appears only when there is something to reset.
function fieldRow({ key, i, name, hint, original, value, store, set, runKey, label, link, rename }) {
  const row = $('#bld-field-template').content.cloneNode(true);
  const id = `bld-field-${link ? 'link-' : ''}${i}`;
  const el = row.querySelector('label'), area = row.querySelector('textarea');
  el.setAttribute('for', id);
  el.textContent = name;
  area.id = id;
  area.value = value;
  if (link) area.rows = 1;
  const help = row.querySelector('.rux--form__helper-text');
  const reset = row.querySelector('button');
  const sync = () => {
    const edited = Object.hasOwn((store[state.template] ?? {})[key] ?? {}, i);
    // THE ORIGINAL SITS BESIDE THE FIELD while it differs — reset lets someone
    // undo a change, but only this lets them see what they are changing.
    help.textContent = edited ? `original: ${original}` : (hint ?? '');
    help.hidden = !help.textContent;
    reset.hidden = !edited;
  };
  sync();
  area.addEventListener('input', event => {
    // A NATIVE FIELD UNDO IS NOT PART OF THE RUN. The browser owns the
    // undo stack inside a textarea; when it fires one, end our run so the
    // change gets an entry of its own rather than joining the typing it
    // just reversed. The two stacks stay separate, which is stated rather
    // than papered over.
    if (event.inputType && event.inputType.startsWith('history')) endRun();
    typed(runKey, label, () => set(area.value));
    sync();
    if (rename) rename(area.value);
    later();
  });
  area.addEventListener('blur', endRun);
  reset.addEventListener('click', () => {
    change(`reset one field in ${labelOf(key)}`, () => { dropOne(store, key, i); });
    area.value = original;
    sync();
    if (rename) rename(original);
    // The button it was clicked on has just gone; without this, focus falls to
    // the document and the reader loses their place mid-panel.
    area.focus();
    later();
  });
  return row;
}

// Record or prune one override, then keep Reset honest. No history of its
// own: typed() wraps it. One function over both stores, so the pruning rule —
// typing a value back to its original deletes it — cannot drift between them.
function setIn(store, key, i, value, original) {
  const forTemplate = store[state.template] ??= {};
  const forEntry = forTemplate[key] ??= {};
  if (value === original) delete forEntry[i]; else forEntry[i] = value;
  if (!Object.keys(forEntry).length) delete forTemplate[key];
  if (!Object.keys(forTemplate).length) delete store[state.template];
  syncReset();
}
const setEdit = (key, i, value, original) => setIn(state.edits, key, i, value, original);
const setLink = (key, i, value, original) => setIn(state.links, key, i, value, original);
const setVariant = (key, i, value, original) => setIn(state.variants, key, i, value, original);

// One field back to its original — the per-field reset. Returns whether it
// changed anything, so change() can record nothing when it did not.
function dropOne(store, key, i) {
  const forTemplate = store[state.template];
  const forEntry = forTemplate?.[key];
  if (!forEntry || !Object.hasOwn(forEntry, i)) return false;
  delete forEntry[i];
  if (!Object.keys(forEntry).length) delete forTemplate[key];
  if (!Object.keys(forTemplate).length) delete store[state.template];
  return true;
}

// REMOVING A BLOCK DROPS BOTH KINDS. Its words and where they pointed go with
// it, or undo brings back a block carrying half its content.
function dropEdits(keys) {
  for (const store of [state.edits, state.links, state.variants]) {
    const forTemplate = store[state.template];
    if (!forTemplate) continue;
    for (const k of keys) delete forTemplate[k];
    if (!Object.keys(forTemplate).length) delete store[state.template];
  }
}

const countFor = key => Object.keys(editsFor(state.template, key)).length + Object.keys(linksFor(state.template, key)).length + Object.keys(variantsFor(state.template, key)).length;
const syncReset = () => { $('#bld-reset').disabled = !countFor(state.block); };
const editCount = () => [state.edits, state.links, state.variants]
  .reduce((n, store) => n + Object.values(store[state.template] ?? {}).reduce((m, b) => m + Object.keys(b).length, 0), 0);

const option = (value, text) => {
  const o = document.createElement('option');
  o.className = 'rux--select-option';
  o.value = value; o.textContent = text;
  return o;
};

// The chosen template's slots, and what the chosen one is a container of.
function fillSlots() {
  const t = templateOf(state.template);
  const select = $('#bld-slot');
  select.textContent = '';
  for (const s of t.slots) select.append(option(s.name, s.name));
  state.slot = t.slots.some(s => s.name === state.slot) ? state.slot : t.slots[0].name;
  select.value = state.slot;
  slotNote();
}

function slotNote() {
  const s = templateOf(state.template).slots.find(x => x.name === state.slot);
  const col = s.container?.column ? short(s.container.column) : 'no grid column recorded';
  const stack = s.container?.stack ? short(s.container.stack) : 'no stack — blocks sit flush (composing-pages §3.5)';
  $('#bld-slot-note').textContent = `${col} · ${stack}`;
}

// THE CATALOGUE, IN TWO GROUPS, AND NOTHING IS REFUSED. page.mjs:45 decided
// that every block is offered in every slot; this sorts and labels, it does not
// gate. The first select holds the blocks whose RECORDED LAYOUT matches this
// slot's -- same grid, column and stack classes -- and the disclosure below
// holds the rest. That is evidence about a placement and never a verdict on
// one: only a block in its own slot is an attested placement, which is why the
// label reads "seen in the same recorded layout" and not "attested here".
//
// Both groups are refilled whenever the SLOT changes, because the split is a
// property of the slot and not of the catalogue.
function fillCatalogue() {
  const slot = templateOf(state.template).slots.find(x => x.name === state.slot);
  const { matched, unmatched } = offerFor(manifest, templateOf(state.template), slot);
  const fill = (sel, list, keep) => {
    sel.textContent = '';
    for (const b of list) sel.append(option(b.id, `${b.label} · ${b.source.replace(/\.html$/, '')}`));
    sel.disabled = !list.length;
    const want = list.some(b => b.id === keep) ? keep : list[0]?.id ?? '';
    sel.value = want;
    return want;
  };
  state.catalogue = fill($('#bld-catalogue'), matched, state.catalogue);
  state.rest = fill($('#bld-rest'), unmatched, state.rest);
  $('#bld-rest-title').textContent = `No matching recorded layout (${unmatched.length})`;
  $('#bld-catalogue-note').textContent = matched.length
    ? `${matched.length} of ${manifest.blocks.length} blocks were recorded in a container with this slot's grid, column and stack classes. That is evidence, not a verdict: only a block in its own slot is an attested placement. Added to the end of the slot.`
    : `No block in the catalogue was recorded in a layout like this one, so everything is under the disclosure below. Added to the end of the slot.`;
  frameNote();
  renderSuggestions();
}

// WHAT THE BLOCK NEEDS FROM THE FRAME, BEFORE IT IS ADDED. The composed page's
// integrity() already reports the same {attr, id} records AFTER an add; this
// says it first, off the destination template's own ids, so the reader is not
// told about a broken reference only once they have made one.
function frameNote() {
  const t = templateOf(state.template);
  const src = templates.get(state.template);
  for (const [sel, note] of [['#bld-catalogue', '#bld-frame-note'], ['#bld-rest', '#bld-rest-frame-note']]) {
    const el = $(note), b = blocks.get($(sel).value);
    const missing = b && src ? frameNeedsMissing(b, src) : [];
    el.hidden = !missing.length;
    if (missing.length) {
      el.textContent = `${b.label} points at ${missing.map(n => `${n.attr}="${n.id}"`).join(' and ')}, which ${t.name} does not have. `
        + `In ${b.source.replace(/^templates\//, '').replace(/\.html$/, '')} that target sits in the frame, outside every block, so it does not travel with this one.`;
    }
  }
}

// THE MAP'S SUGGESTIONS. PROMOTED IS reviewed === true AND NOTHING ELSE --
// rux's review: visual priority is authority whatever a badge says, so a draft
// never takes the top of the list. Everything ships unreviewed, so this section
// is a closed "not reviewed" disclosure today and that is the intended state.
function renderSuggestions() {
  const box = $('#bld-suggestions');
  box.textContent = '';
  if (!guide) { box.hidden = true; return; }
  const { purpose, purposeReviewed, promoted, drafts } = suggestionsFor(guide, state.template);
  // EVERY SLOT'S SUGGESTIONS, not the picked slot's: a suggestion names its
  // own slot and its Add passes that slot explicitly, so the slot select
  // below is for inspecting the catalogue and never rewritten behind the
  // reader's back. Until stage 12 this filtered by state.slot.
  const mine = promoted, draft = drafts;
  if (!purpose && !mine.length && !draft.length) { box.hidden = true; return; }
  box.hidden = false;

  if (purpose) {
    const p = document.createElement('p');
    p.className = 'bld-status';
    p.textContent = purposeReviewed ? purpose : `${purpose} (not reviewed)`;
    box.append(p);
  }
  const list = (items, heading, open) => {
    if (!items.length) return;
    // The accordion comes from the page's own <template>, the idiom every other
    // panel here uses: the markup stays in builder.html where the markup gates
    // and the sink diff can see it, rather than in a string in this file.
    const frag = $('#bld-suggest-group-template').content.cloneNode(true);
    const item = frag.querySelector('.rux--accordion__item');
    const head = frag.querySelector('.rux--accordion__heading');
    if (open) { item.classList.add('rux--accordion__item--active'); head.setAttribute('aria-expanded', 'true'); }
    frag.querySelector('.rux--accordion__title').textContent = `${heading} (${items.length})`;
    const body = frag.querySelector('.rux--accordion__content');
    for (const s of items) {
      const one = $('#bld-suggest-template').content.cloneNode(true);
      const at = r => one.querySelector(`[data-role="${r}"]`);
      const many = templateOf(state.template).slots.length > 1;
      at('reason').textContent = `${blocks.get(s.block)?.label ?? s.block}${many ? ` in ${s.slot}` : ''} — ${s.reason}`;
      if (s.unless) { at('unless').textContent = `Not when: ${s.unless}`; at('unless').hidden = false; }
      if (s.evidence) { at('evidence').textContent = `Unverified: ${s.evidence}`; at('evidence').hidden = false; }
      // data-act, not data-role: check-aria-roles reads `role="` wherever it
      // appears, and a classed button carrying data-role="add" read as a
      // role Carbon never renders.
      const add = one.querySelector('[data-act="add"]');
      add.textContent = `Add ${blocks.get(s.block)?.label ?? 'it'}`;
      add.addEventListener('click', () => addBlock(s.block, s.slot));
      body.append(one);
    }
    box.append(frag);
  };
  list(mine, 'Suggested here', true);
  list(draft, 'Draft suggestions — not reviewed', false);
}

// Fill the block picker from the model, in document order, by label; a
// second instance is numbered, and on a template with several slots the slot
// leads. `keep` is the key to leave selected when it is still on the page.
function fillPicker(keep = state.block) {
  const t = templateOf(state.template);
  const es = entries();
  const select = $('#bld-block');
  select.textContent = '';
  for (const e of es) {
    const b = blocks.get(e.id);
    select.append(option(e.key, `${t.slots.length > 1 ? `${e.slot} · ` : ''}${b.label}${e.n > 1 ? ` (${e.n})` : ''}`));
  }
  state.block = es.some(e => e.key === keep) ? keep : (es[0]?.key ?? '');
  select.value = state.block;
  showBlock();
}

// The panel, the note, the buttons and the preview highlight for whichever
// entry is selected. Nothing about the composed page changed by choosing one,
// so the frame is not reloaded.
function showBlock() {
  const e = entryOf(state.block);
  renderFieldPanel(state.block, e ? blocks.get(e.id).html : '');
  blockNote(e);
  syncButtons(e);
  syncReset();
  syncKeep();
  fillOutline();
  highlight();
}

// Where the block was attested, and what it moves with. Information, not a
// rule: the arrangement is the reader's.
function blockNote(e) {
  const note = $('#bld-block-note');
  if (!e) { note.textContent = 'Nothing on the page. Add a block from the catalogue.'; return; }
  const b = blocks.get(e.id);
  const where = b.kind === 'component'
    ? `Attested in the kitchen sink, ${b.source}.`
    : `Attested in ${b.source.replace(/^templates\//, '').replace(/\.html$/, '')}: ${short(b.column) || 'no column'} · ${b.stack ? short(b.stack) : 'no stack'}.`;
  const u = unitOf(pageOf(), e.key);
  const rides = e.follows ? ` Moves and goes with ${labelOf(u.keys[0])}.`
    : u.keys.length > 1 ? ` ${u.keys.slice(1).map(labelOf).join(', ')} moves and goes with it.` : '';
  note.textContent = where + rides;
}

function syncButtons(e) {
  const up = $('#bld-up'), down = $('#bld-down'), rm = $('#bld-remove');
  if (!e) { up.disabled = down.disabled = rm.disabled = true; return; }
  const page = pageOf(), u = unitOf(page, e.key);
  up.disabled = u.start === 0;
  down.disabled = u.end >= page.slots[u.slot].length;
  rm.disabled = false;
}

// Best-effort, and only that: the preview is a document of its own and this
// draws on it. The block's own BLOCK:BEGIN/END comments survive into it, so the
// run of element siblings between them is the block — a run, not one element,
// because a block can have several roots (app-shell's page-title is <h1>+<p>).
// A page may carry the same marker name more than once — a block placed twice,
// or two sources that both call theirs `default` — and the k-th marker in the
// document is the k-th entry with that name in the model, because composePage
// emits slots in template order and entries in model order. Each target's
// existing inline outline is saved and restored rather than blanked, so the
// helper stays non-destructive even though nothing ships one.
let highlighted = [];
function highlight() {
  for (const h of highlighted) { h.el.style.outline = h.outline; h.el.style.outlineOffset = h.offset; }
  highlighted = [];
  const doc = frame.contentDocument;
  const e = entryOf(state.block);
  if (!doc || !doc.body || !e) return;
  const name = blocks.get(e.id).name;
  const k = entries().filter(x => blocks.get(x.id).name === name).findIndex(x => x.key === e.key);
  const walk = doc.createTreeWalker(doc.body, NodeFilter.SHOW_COMMENT);
  let begin = null, seen = 0;
  for (let n; (n = walk.nextNode());) if (n.nodeValue.includes(`BLOCK:BEGIN name=${name} `) && seen++ === k) { begin = n; break; }
  if (!begin) return;
  for (let n = begin.nextSibling; n; n = n.nextSibling) {
    if (n.nodeType === Node.COMMENT_NODE && n.nodeValue.includes(`BLOCK:END ${name}`)) break;
    if (n.nodeType !== Node.ELEMENT_NODE) continue;
    highlighted.push({ el: n, outline: n.style.outline, offset: n.style.outlineOffset });
    n.style.outline = '2px dashed var(--rux-border-interactive)';
    n.style.outlineOffset = '2px';
  }
}

const plural = (n, w) => `${n} ${w}${n === 1 ? '' : 's'}`;

let pending = null;
let openUrl = null;
async function render() {
  const my = pending = {};
  // BEFORE THE TRY, because neither depends on the composition: the command is
  // built from the answers and the template alone, and it must still be right
  // on a page whose preview failed to build.
  $('#bld-command').textContent = command();
  exportWarning();
  try {
    const { page, roundTrip, integrity: ig } = await composed();
    if (pending !== my) return;
    const doc = previewPage(page, answers(), ROOT);
    const url = URL.createObjectURL(new Blob([doc], { type: 'text/html' }));
    frame.addEventListener('load', () => { URL.revokeObjectURL(url); highlighted = []; highlight(); }, { once: true });
    frame.src = url;
    const t = templateOf(state.template);
    const es = entries();
    const natives = t.slots.reduce((n, s) => n + s.blocks.length, 0);
    const kept = es.filter(e => isNative(e, t)).length;
    const arranged = [es.length - kept ? `${es.length - kept} added` : '', natives - kept ? `${natives - kept} removed` : ''].filter(Boolean).join(', ');
    const edits = editCount();
    status.textContent = [
      `${state.template} · ${plural(t.slots.length, 'slot')}, ${plural(es.length, 'block')}${arranged ? ` (${arranged})` : ''}`,
      `round trip ${roundTrip ? 'identical' : 'DIFFERS'}`,
      ig.duplicateIds.length ? `${plural(ig.duplicateIds.length, 'id')} DUPLICATED` : 'ids unique',
      ig.unresolved.length ? `${plural(ig.unresolved.length, 'reference')} unresolved` : 'references resolved',
      state.width === 'fit' ? 'fit to pane' : `${state.width}px`,
      edits ? `${plural(edits, 'field')} edited` : '',
    ].filter(Boolean).join(' · ');
    const named = new Map();
    for (const id of ig.duplicateIds) named.set(`id="${id}" twice or more`, 1);
    for (const r of ig.unresolved) { const k = `${r.attr}="${r.attr === 'href' || r.attr === 'xlink:href' ? '#' : ''}${r.id}"`; named.set(k, (named.get(k) ?? 0) + 1); }
    integrityLine.textContent = named.size ? `On this page: ${[...named].map(([k, n]) => n > 1 ? `${k} ×${n}` : k).join(' · ')}` : '';
    integrityLine.hidden = !named.size;
    // THE SAME READINGS IN PLAIN WORDS, for the Review step. The status line
    // above keeps the gate vocabulary; this says what it means.
    const problems = [];
    if (ig.duplicateIds.length) problems.push(`${plural(ig.duplicateIds.length, 'id')} used more than once, so a label or a link can land on the wrong element`);
    if (ig.unresolved.length) problems.push(`${plural(ig.unresolved.length, 'reference')} pointing at something not on this page`);
    if (!roundTrip) problems.push('the builder could not reproduce the untouched template byte for byte, which is a builder fault and not yours');
    $('#bld-review').textContent = problems.length
      ? `Not yet whole: ${problems.join('; ')}. ${named.size ? `On this page: ${[...named].map(([k, n]) => n > 1 ? `${k} ×${n}` : k).join(' · ')}.` : ''} Remove or repoint the part that does it, or take the page as it is knowing that.`
      : `Holds together: ${plural(es.length, 'section')}, every id unique, every reference resolved${edits ? `, ${plural(edits, 'field')} edited` : ''}. What no check reads is the arrangement — docs/composing-pages.md §3.10.`;
    // A real link to the same document, for a real browser's new tab. The
    // frame's URL is revoked on load, so this is a second one, released when
    // the next render replaces it.
    if (openUrl) URL.revokeObjectURL(openUrl);
    openUrl = URL.createObjectURL(new Blob([doc], { type: 'text/html' }));
    $('#bld-open').href = openUrl;
  } catch (e) {
    status.textContent = `Could not build the preview: ${e.message}`;
  }
}

function setWidth(w) {
  state.width = w;
  for (const b of document.querySelectorAll('[data-width]')) b.setAttribute('aria-pressed', String(b.dataset.width === w));
  if (w === 'fit') {
    frame.style.inlineSize = '100%';
    wrap.style.transform = '';
    wrap.style.blockSize = '';
    wrap.style.inlineSize = '';
  } else {
    const px = Number(w);
    const pane = wrap.parentElement.clientWidth;
    const scale = Math.min(1, pane / px);
    frame.style.inlineSize = `${px}px`;
    wrap.style.inlineSize = `${px}px`;
    wrap.style.transform = scale < 1 ? `scale(${scale})` : '';
    wrap.style.blockSize = scale < 1 ? `${frame.getBoundingClientRect().height * scale}px` : '';
  }
  render();
}

let timer;
const later = () => { clearTimeout(timer); timer = setTimeout(render, 250); };

// The three arrangements. Each is one transaction: the pure transition, the
// edits that go with it, and nothing else.
// ONE ADD, TWO PATHS INTO IT. The disclosure's button and the matched group's
// button differ only in which select they read; the transaction is the same, so
// there is no second code path for an unmatched block to drift down.
// THE SLOT IS A PARAMETER, defaulting to the picked one: a suggestion's Add
// names its own slot and must not rewrite the select behind the reader.
function addBlock(id, slot = state.slot) {
  if (!id) return;
  const label = blocks.get(id)?.label ?? 'block';
  let placed = null;
  change(`add ${label}`, () => {
    setPage(add(pageOf(), slot, id, manifest));
    const list = pageOf().slots[slot];
    placed = unitOf(pageOf(), list[list.length - 1].key).keys[0];
  });
  fillPicker(placed ?? state.block);
  render();
}

function moveBlock(dir) {
  if (!state.block) return;
  const label = labelOf(state.block), key = state.block;
  change(`move ${label} ${dir < 0 ? 'up' : 'down'}`, () => setPage(move(pageOf(), key, dir)));
  fillPicker(key);
  render();
}

function removeBlock() {
  if (!state.block) return;
  const es = entries();
  const u = unitOf(pageOf(), state.block);
  const at = es.findIndex(e => e.key === u.keys[0]);
  const label = labelOf(u.keys[0]);
  // ONE ENTRY, THOUGH IT TOUCHES TWO THINGS. The block's text goes with the
  // block; undo brings both back together or the reader has lost their words
  // to a button that said Remove.
  change(`remove ${label}`, () => {
    dropEdits(u.keys);
    setPage(remove(pageOf(), state.block));
  });
  const rest = entries();
  fillPicker(rest[Math.min(at, rest.length - 1)]?.key ?? '');
  render();
}

// ── taking it away ─────────────────────────────────────────────────────────
//
// ONE DEFINITION OF THE FILE NAME, used by the download and by the command,
// because the two would otherwise disagree in a way nobody sees until the
// script dies. `page` is a FILE NAME, never a path: new-project.sh writes
// `> "$DIR/$PAGE.html"` and creates no parent directory, so `reports/orders`
// kills it under `set -e`, while a browser's download attribute quietly
// flattens the separator and writes the file anyway. A trailing `.html` is
// stripped rather than rejected — the field says "without .html", and typing
// it is the obvious slip, not an error worth a lecture.
function normalisePage() {
  const raw = state.page.trim().replace(/\.html$/i, '');
  if (!raw || /[/\\]/.test(raw)) return { name: 'index', why: raw ? `“${raw}” has a path separator; the script writes one file beside the project's own index.html` : '' };
  return { name: raw, why: '' };
}

// Every answer single-quoted, so nothing in it is read by the shell. The
// FOLDER IS DELIBERATELY ABSENT: supplying every other flag leaves the script
// asking exactly one question, first, with its own default. The builder does
// not know the reader's folders, and a placeholder path they might run without
// reading is the trap this avoids.
const sq = s => `'${String(s).split("'").join("'\\''")}'`;
function command() {
  const a = answers();
  return ['./tools/new-project.sh',
    '--template', sq(state.template), '--theme', sq(a.theme), '--grid', sq(a.grid),
    '--prefix', sq(a.prefix), '--name', sq(a.name),
    '--title', sq(a.title), '--page', sq(normalisePage().name)].join(' ');
}

// NEITHER SIDE ESCAPES HTML, and check-parity says so in its own words: an
// answer carrying " < > or & lands unescaped in element text and in an
// aria-label, so it can make markup both sides agree on byte for byte and no
// browser reads as intended. The builder will not escape unilaterally — that
// would break the parity contract it just earned — so it says so instead.
// Whether to escape in both, reject in both, or leave it is rux's: §4.12.
function exportWarning() {
  const a = answers();
  const bad = [['product prefix', a.prefix], ['product name', a.name], ['browser tab title', a.title]]
    .map(([label, v]) => [label, [...new Set((v.match(/["<>&]/g) ?? []))].join(' ')])
    .filter(([, chars]) => chars);
  const line = $('#bld-export-warn');
  const page = normalisePage();
  const notes = [
    bad.length ? `${bad.map(([l, c]) => `the ${l} carries ${c}`).join(', ')} — neither the export nor new-project.sh escapes these, so the page may not read as you intend.` : '',
    page.why,
  ].filter(Boolean);
  line.textContent = notes.join(' ');
  line.hidden = !notes.length;
}

async function downloadPage() {
  try {
    const doc = exportPage((await composed()).page, answers());
    const url = URL.createObjectURL(new Blob([doc], { type: 'text/html' }));
    // An unclassed anchor, the way decodeText() makes an unclassed textarea:
    // this file invents no rux-- markup, and neither of these is any.
    const a = document.createElement('a');
    a.href = url;
    a.download = `${normalisePage().name}.html`;
    a.click();
    // NOT REVOKED ON THE NEXT LINE. The preview's URL is revoked on the
    // iframe's `load`, because there the consumer announces it has the bytes;
    // a download announces nothing, and revoking in the same tick as the click
    // has been observed to abort the save. So it is released on a timer — long
    // enough that the browser has taken it, short enough that a session of
    // exports does not accumulate documents in memory.
    setTimeout(() => URL.revokeObjectURL(url), 10_000);
    exportNotice('Downloaded', `${a.download} — put it beside the project's own index.html. Its paths already point at /rux-ds/.`);
  } catch (e) {
    exportAlert('Could not build the page', e.message);
  }
}

async function copyText(what, text, subtitle) {
  try {
    await navigator.clipboard.writeText(text);
    exportNotice(`${what} copied`, subtitle);
  } catch (e) {
    // The same call js/copy-button.js makes, and the same reason it does not
    // go silent: a copy that failed and said nothing is worse than one that
    // says where to look.
    exportAlert(`Could not copy the ${what.toLowerCase()}`, `${e.message}. It is on window.RuxBuilder if you need it from the console.`);
  }
}

async function init() {
  try {
    manifest = JSON.parse(await fetchText('builder/blocks.json'));
  } catch (e) {
    status.textContent = `Could not load builder/blocks.json: ${e.message}. Serve this repository (node tools/serve.mjs) rather than opening the file.`;
    return;
  }
  for (const b of manifest.blocks) blocks.set(b.id, b);
  // THE MAP IS NOT LOAD-BEARING. The catalogue's split is derived from the
  // manifest, so a missing or unreadable guide.json costs the purpose line and
  // the suggestions and nothing else. It is validated by check-blocks; there is
  // no second validation here that could disagree with it.
  try { guide = JSON.parse(await fetchText('builder/guide.json')); }
  catch { guide = null; }
  const select = $('#bld-template');
  for (const t of manifest.templates) select.append(option(t.name, t.name));

  openDraft();                       // before the first render, after the manifest

  select.value = state.template;
  select.addEventListener('change', () => selectTemplate(select.value));
  for (const r of document.querySelectorAll('input[name="bld-purpose"]')) r.addEventListener('change', () => { if (r.checked) selectTemplate(r.value); });
  for (const b of document.querySelectorAll('[data-mode]')) b.addEventListener('click', () => { endRun(); setMode(b.dataset.mode); });
  for (const b of document.querySelectorAll('#bld-stepper [data-step]')) b.addEventListener('click', () => { endRun(); setStep(Number(b.dataset.step)); });
  $('#bld-back').addEventListener('click', () => { endRun(); setStep(state.step - 1); });
  $('#bld-next').addEventListener('click', () => { endRun(); setStep(state.step + 1); });
  $('#bld-keep').addEventListener('click', keepSettings);
  const slot = $('#bld-slot');
  slot.addEventListener('change', () => { endRun(); state.slot = slot.value; slotNote(); fillCatalogue(); });
  const catalogue = $('#bld-catalogue');
  catalogue.addEventListener('change', () => { endRun(); state.catalogue = catalogue.value; frameNote(); });
  const rest = $('#bld-rest');
  rest.addEventListener('change', () => { endRun(); state.rest = rest.value; frameNote(); });
  $('#bld-add').addEventListener('click', () => addBlock(state.catalogue));
  $('#bld-add-rest').addEventListener('click', () => addBlock(state.rest));
  $('#bld-up').addEventListener('click', () => moveBlock(-1));
  $('#bld-down').addEventListener('click', () => moveBlock(+1));
  $('#bld-remove').addEventListener('click', removeBlock);
  $('#bld-undo').addEventListener('click', () => step('undo'));
  $('#bld-redo').addEventListener('click', () => step('redo'));
  $('#bld-start-over').addEventListener('click', startOver);
  $('#bld-download').addEventListener('click', downloadPage);
  $('#bld-copy').addEventListener('click', async () => {
    try {
      const main = bodyOnly(exportPage((await composed()).page, answers()));
      if (!main) return exportAlert('Nothing to copy', 'this page has no <main> region.');
      await copyText('Main region', main, 'It is the whole <main> element, so it REPLACES the main region of the page you paste it into.');
    } catch (e) { exportAlert('Could not build the page', e.message); }
  });
  $('#bld-copy-command').addEventListener('click', () =>
    copyText('Command', command(), 'Run it from your rux-ds clone; it will ask where to put the project.'));
  const picker = $('#bld-block');
  picker.addEventListener('change', () => { endRun(); state.block = picker.value; showBlock(); });
  $('#bld-reset').addEventListener('click', () => {
    const key = state.block;
    change(`reset ${labelOf(key)}`, () => dropEdits([key]));
    showBlock();
    later();
  });
  for (const r of document.querySelectorAll('input[name="bld-theme"]')) {
    r.addEventListener('change', () => {
      if (!r.checked) return;
      change(`theme ${r.nextElementSibling?.textContent.trim() || r.value}`, () => { state.theme = r.value; });
      render();
    });
  }
  for (const r of document.querySelectorAll('input[name="bld-grid"]')) {
    r.addEventListener('change', () => {
      if (!r.checked) return;
      change(`grid ${r.nextElementSibling?.textContent.trim() || r.value}`, () => { state.grid = r.value; });
      render();
    });
  }
  for (const [id, key] of FIELDS) {
    const input = $(`#${id}`);
    input.addEventListener('input', event => {
      if (event.inputType && event.inputType.startsWith('history')) endRun();
      typed(id, `${key === 'page' ? 'file name' : key}`, () => { state[key] = input.value; });
      later();
    });
    input.addEventListener('blur', endRun);
  }
  for (const b of document.querySelectorAll('[data-width]')) b.addEventListener('click', () => setWidth(b.dataset.width));
  window.addEventListener('resize', () => { if (state.width !== 'fit') setWidth(state.width); });

  // The field's own undo owns the field. Everywhere else, ours does.
  document.addEventListener('keydown', event => {
    if (!(event.metaKey || event.ctrlKey) || event.key.toLowerCase() !== 'z') return;
    const t = event.target;
    if (t && (t.tagName === 'TEXTAREA' || (t.tagName === 'INPUT' && t.type === 'text'))) return;
    event.preventDefault();
    step(event.shiftKey ? 'redo' : 'undo');
  });
  // A debounce is a promise to write in half a second, which a reload does
  // not wait for. Both events, because neither fires reliably alone.
  window.addEventListener('pagehide', flushSave);
  document.addEventListener('visibilitychange', () => { if (document.visibilityState === 'hidden') flushSave(); });

  // FILL THE SLOTS FIRST. The catalogue's split is a property of the SLOT, so
  // it cannot be computed before state.slot has a value.
  fillSlots();
  fillCatalogue();
  fillPicker();
  fillPurpose();
  syncHistory();
  // The view, last: the sections exist and the step's heading can take focus,
  // but on load nothing is focused — a page that grabs focus on open is a
  // page that steals it from the address bar.
  const view = readView() ?? { mode: 'guided', step: 1 };
  if (view.template && manifest.templates.some(t => t.name === view.template) && view.template !== state.template) {
    state.template = view.template;
    select.value = view.template;
    fillSlots(); fillCatalogue(); fillPicker(); fillPurpose();
  }
  state.step = view.step;
  setMode(view.mode, false);
  setStep(view.step, false);
  render();
}

// For the console and the gates' operator: the page the export would write,
// the model, the history, and every action driven without the buttons.
window.RuxBuilder = {
  state,
  page: async () => exportPage((await composed()).page, answers()),
  main: async () => bodyOnly(exportPage((await composed()).page, answers())),
  command,
  fileName: normalisePage,
  download: downloadPage,
  roundTrip: async () => (await composed()).roundTrip,
  integrity: async () => (await composed()).integrity,
  model: () => pageOf(),
  history: () => ({ past: history.past.map(e => e.label), future: history.future.map(e => e.label) }),
  run: () => (run ? { key: run.key, age: Date.now() - run.at } : null),
  add: (slot, id) => { state.slot = slot; addBlock(id); },
  move: (key, dir) => { state.block = key; moveBlock(dir); },
  remove: key => { state.block = key; removeBlock(); },
  undo: () => step('undo'),
  redo: () => step('redo'),
  startOver,
  flushSave,
  mode: () => state.mode,
  step: () => state.step,
  setMode: m => setMode(m, false),
  setStep: n => setStep(n, false),
  keepSettings,
  // Exposed so the no-fields branch — which no shipped block triggers — can be
  // driven through the real clone-into-DOM path rather than left untested.
  renderFieldPanel,
};

init();
