#!/usr/bin/env node
//
// SPLICES THE SHARED SHELL INTO A HAND-WRITTEN PAGE.
//
// tools/lib/shell.mjs emits one shell and the four generated pages call it
// directly. index.html is not generated — it is hand-written, it carries prose
// and a tile grid nobody wants to express in a template literal, and it was
// therefore the one page left with a shell of its own. Pasting the shared one
// into it would have recreated the fifth copy the shared file exists to
// remove, so it is spliced instead, between two markers, the same way
// tools/icons.mjs splices the sprite into templates/.
//
// A FILE OPTS IN BY CARRYING THE MARKERS. Nothing is scanned for, nothing is
// guessed: the page declares where its shell goes and which page it is.
//
//   <!-- SHELL:BEGIN index — generated by tools/inline-shell.mjs, do not edit -->
//   ...anything here is replaced...
//   <!-- SHELL:END -->
//
// It is idempotent and it is checked in: running it twice writes the same
// bytes, and the result is committed so a clone with no build step still
// serves a correct page.
//
import { readFileSync, writeFileSync } from 'node:fs';
import { shell, PAGES } from './lib/shell.mjs';

const BEGIN = /<!-- SHELL:BEGIN ([a-z-]+)[^>]*-->/;
const END = '<!-- SHELL:END -->';

const TARGETS = ['index.html'];
let wrote = 0;

for (const file of TARGETS) {
  const text = readFileSync(file, 'utf8');
  const open = BEGIN.exec(text);
  if (!open) {
    console.error(`  ${file}: no SHELL:BEGIN marker — nothing to splice`);
    process.exit(1);
  }
  const page = open[1];
  if (!PAGES.some(p => p.id === page)) {
    console.error(`  ${file}: SHELL:BEGIN names "${page}", which is not a page in tools/lib/shell.mjs`);
    process.exit(1);
  }
  const endAt = text.indexOf(END, open.index);
  if (endAt === -1) {
    console.error(`  ${file}: SHELL:BEGIN with no SHELL:END`);
    process.exit(1);
  }
  const next = text.slice(0, open.index + open[0].length) + '\n'
    + shell(page) + '\n' + text.slice(endAt);
  if (next !== text) { writeFileSync(file, next); wrote++; }
  console.log(`  ${file} — shell spliced as "${page}"${next === text ? ' (unchanged)' : ''}`);
}

if (!wrote) console.log('  nothing changed');
